### ISSUE TITLE
Sleuth converter failing on multiline experiment names

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#129]
The Sleuth-to-json converter is failing on any experiment labels that are more than one line long. This applies both to very long names that are wrapped and to grouped experiments (one of the options for Sleuth exporting). It should be pretty easy to fix.

**Comment by tsalo** [comment]
@nicholst I'm finally getting around to this. Would you mind sharing one of the text files that failed to convert at the hackathon, so I have something to test against?

**Comment by nicholst** [comment]
Sure! Here are 3 versions, collected off Sleuth in 2015 and a few weeks ago:

https://www.dropbox.com/s/tckk6xon4foewlg/Sleuth-2015.txt?dl=0
https://www.dropbox.com/s/mz7r5idlghcnvln/Sleuth-2019.txt?dl=0
https://www.dropbox.com/s/rux71vgto9bzeuu/Sleuth-2019-Grouped.txt?dl=0

**Comment by tsalo** [comment]
Thank you! It looks like my changes will successfully work around multiline experiment names, although the names _will_ end up looking kind of ugly. For example, the second study in the grouped dataset you attached:

```
// Sommer M, 2007: Conjunction of True and False Belief
// Sommer M, 2007: False Belief > True Belief
// Sommer M, 2007: True Belief > False Belief
// Subjects=16
```

will end up with the ID `Sommer M, 2007-Conjunction of True and False Belief Sommer M, 2007: False Belief > True Belief Sommer M, 2007: True Belief > False Belief`, which breaks down into the study ID `Sommer M, 2007` and the contrast ID `Conjunction of True and False Belief Sommer M, 2007: False Belief > True Belief Sommer M, 2007: True Belief > False Belief`.

This should be fine as long as datasets are treated as immutable objects (which is the long-term goal), but does make searching the datasets a little awkward. Hopefully once Neurostuff/Neurostore is up and running, we'll be able to use more concise identifiers (like PMIDs or DOIs) across all databases.

**Comment by nicholst** [comment]
This sounds fine.  Thanks for chasing this up!

BTW, will NiMARE work with the old and new Sleuth files?

**Comment by tsalo** [comment]
It should work fine with both. The old files seem to have the wrapping issue for very long study names, while the new files seem to have both the wrapping issue and the grouping. The changes proposed in #146 should be able to handle both. Unless there are other differences I wasn't aware of?

**Comment by nicholst** [comment]
I really don't have much experience... just have those files I sent kicking
around.

**Comment by angielaird** [comment]
I'll check in with Mick and Angela in San Antonio to see if there may be other differences.

**Comment by angielaird** [comment]
No other differences to report from San Antonio 👍

**Comment by tsalo** [comment]
Thanks @angielaird. I'll merge #146 and close this then.
