### ISSUE TITLE
Should we include text extraction/automated annotation tools?

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#13]
Both functional decoding and content-based meta-analyses will require some way of labeling experiments/papers. By grabbing labeled images from Neurovault and crowd-annotated experiments from Brainspell, we can build datasets with manual annotations, *but* I was thinking that it might be a good idea to support automated annotation methods as well.

We could have a submodule of `nimare.extract` for text extraction (e.g., downloading abstracts, tf-idf vectorization of abstracts with a data-driven ontology like Neurosynth, LDA topic modeling, GCLDA topic modeling, Cognitive Atlas term extraction, and hierarchical expansion of CogAt labels). Some elements are currently implemented in Neurosynth, while I’ve attempted to implement others in [cogat-extraction](https://github.com/tsalo/cogat-extraction).

**Comment by tyarkoni** [comment]
I think that's a great idea, but before we get too far down that road, it probably makes sense to spend some time thinking about the way we plan to represent label/text/annotation data. We will probably want a single standard that spans NeuroVault, BrainSpell, (the next version of) Neurosynth, and potentially other platforms such as the Cognitive Atlas, etc. That's sufficiently important that it's worth taking the time to get right, so it might be worth drafting a BIDS extension spec for this and then sending it around for community feedback (at minimum, to JB, Chris, Russ, Roberto, Tom, etc.).

**Comment by tsalo** [comment]
That makes sense, and I definitely think it's worth achieving a larger consensus on. I'm not entirely sure where to start though.

**Comment by tsalo** [comment]
At least as a first pass, I think that the Neurosynth format works well, with some adjustments. Namely, annotations can be stored as a spreadsheet linking studies/contrasts (rows) to labels (columns), where the cells can be bools (for manual annotations) or floats (for confidence in automated or crowd-sourced annotations).

The only things that are probably necessary to extend it to other sources are to have NaNs/NULLs for missing annotations and to use some kind of delimiter to separate different annotation sources (e.g., prepending each label with the source, like "mallet.topic001" vs "gclda.topic001").

For NiMARE specifically, it shouldn't be too hard to store the same information in a json, and then to convert it to a spreadsheet to be stored in the `Dataset` object.

**Comment by tsalo** [comment]
I've started working on adding the skeleton for automated annotation tools in #18. Nothing is functional, and it can all be changed at any time, but I figured that it would be good to get some idea of what methods we'd like to include in NiMARE and to figure out how we'd like the API to be set up. Below is a list of methods and associated tools we might want to incorporate:

- Existing ontologies
    - Cognitive Atlas
        - Python API: [cogat-python](https://github.com/CognitiveAtlas/cogat-python)
        - Tool for extraction/hierarchical expansion: [cogat-extraction](https://github.com/tsalo/cogat-extraction)
        - Possible additional tool for extraction: [wordfish](https://github.com/word-fish/wordfish-python)
    - Cognitive Paradigm Ontology
        - ATHENA (in development)
- Topic models
    - Latent Dirichlet allocation (LDA) with MALLET: [Neurosynth](https://github.com/neurosynth/neurosynth/blob/bede56b51011258367f95ad5d8ab93c9aff4bb5e/neurosynth/analysis/reduce.py#L176)
    - Generalized correspondence latent Dirichlet allocation (GCLDA): [python_gclda](https://github.com/timothyrubin/python_gclda) (official package), [gclda](https://github.com/tsalo/gclda) (somewhat refactored version)
    - Global Vectors for Word Representation (GloVe) model: [preprint](https://www.biorxiv.org/content/early/2018/04/11/299024) (no associated code currently available)
    - Deep Boltzmann machines: [DeepTextMining](https://github.com/piomonti/DeepTextMining)

**Comment by tsalo** [comment]
The skeleton has been merged, and I think the answer to this question is a resounding yes, even if power users are the only ones who ever use those tools.
