### ISSUE TITLE
Add option to specify FWHM in ALE CLI

### ISSUE THREAD

**Issue by mriedel56** [neurostuff/NiMARE#134]
For the ALE algorithm, can a command line option be included that allows you to specify the FWHM for the smoothing kernel, rather than determining it from sample sizes?

**Comment by angielaird** [comment]
I like this idea for when we're running tests or simulations.

**Comment by tsalo** [comment]
This is a great idea. FWHM is an optional argument for the Python class, so it will be very easy to add it to the CLI.
