### ISSUE TITLE
Maintain separate classes for different estimators, or include an `estimator` argument?

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#159]
The `FFX_GLM` and `MFX_GLM` classes (and corresponding functions `ffx_glm` and `mfx_glm`) currently rely on FSL. At some point in future it's likely we'll want to give users the option to select between multiple estimators. I would suggest either renaming the classes to, e.g., `FFX_FSL_GLM`, or adding an `estimator` initialization argument that takes a string specifying the estimator to use (which currently would be set to `FSL` in both cases).

The decision between these two should IMO be based on whether we anticipate different estimators requiring their own arguments or not (if yes, then separate names seem desirable; otherwise an `estimator` argument seems okay).

**Comment by tsalo** [comment]
I personally lean toward the first option- maintaining separate classes. It seems like cases where we have multiple estimators for the same process will be pretty rare. For the FSL-based IBMA methods, for example, I think the best plan forward is to actually eliminate the FSL version and to just keep the pure Python version.

**Comment by tyarkoni** [comment]
+1 to eliminating the FSL-based classes (in which case calling the remaining classes `FFX` and `MFX` seems sensible). I've looked into implementing the mixed-effects meta-analysis model and it's totally feasible, it's just a matter of finding a bit of time to work on it. Hoping to get to it next week.

**Comment by tyarkoni** [comment]
I think this is resolved (pending completion of #163), so I'm closing it here.
