### ISSUE TITLE
Continuous integration and test coverage

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#16]
I've only recently started working on writing tests in #15, but would like to set up CI and coverage analysis. I was thinking of using Travis and Coveralls, but am not invested in either. Does anyone have any preferred tools?

**Comment by emdupre** [comment]
I've found [codecov](https://codecov.io/) to be slightly more stable than coveralls !

**Comment by tsalo** [comment]
@emdupre Totally agree. I think I switched to codecov in #15 based on what you used in `tedana`.

**Comment by tsalo** [comment]
Moving over to CircleCI + CodeCov.

**Comment by tsalo** [comment]
I'm really stuck on getting CodeCov working. Between orbs, Webhooks, integrations, upload tokens, and the fact that we're trying to submit reports to CodeCov through CircleCI _within_ a Docker image... I'm just completely lost. If anyone has some experience with this, that would be great.

**Comment by tsalo** [comment]
Resolved with #148 and #150.
