### ISSUE TITLE
Move BiBTeX references to separate module for clarity

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#160]
The BiBTeX references injected into the @due.dcite decorations clutter up some of the modules with a lot of text. We could move these all to their own module (`references`?) and then just import and inject the pre-formatted refs for clarity.

**Comment by tsalo** [comment]
Something like [this](https://github.com/aestrivex/bctpy/blob/master/bct/citations.py)? If so, I can do it.

**Comment by tyarkoni** [comment]
Yep, exactly!
