### ISSUE TITLE
Generalize masking to support both voxel-based and ROI-based analysis

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#175]
Currently we maintain a nibabel volume as a `mask` in `Dataset`, `MetaResult`, etc., and then use nilearn's `apply_mask` and `unmask` utilities to convert to and from arrays. This works fine, but is limiting, as a common use case—particularly once we merge the Stan MFX estimator—is likely to be ROI-based analysis.

The proposal here is to replace most, if not all, of the masking functionality throughout the package with a custom `Masker` class (possibly named something else to avoid conflicts with nilearn) that can seamlessly handle conversion to/from both voxels and ROIs. API changes would be minimal; mainly, we would replace `mask_file` with `mask` everywhere, and users would be able to pass (a) a string, (b) a NiBabel image, or (c) a `Masker` instance. If given the first two, we would internally construct a `Masker` that does voxel-wise extraction. But if given a `Masker`, we would then be able to seamlessly handle ROIs.

Usage example:

```python
# Current usage with MNI152 default still works fine
dataset = Dataset("source.json")

# Specifying custom mask only changes argument name
dataset = Dataset("source.json", mask='mymask.nii.gz')

# Use ROI-level extraction with custom mask
m = Masker("mask.nii.gz", regions=True)
dataset = Dataset("source.json", mask=m)
```

Thoughts? I feel pretty strongly that this is going to make life substantially easier when working with computationally intensive models, but let me know if you have any objections, @tsalo .

**Comment by tsalo** [comment]
Instead of writing our own `Masker`, could we support the various nilearn maskers?

**Comment by tyarkoni** [comment]
I considered that, but AFAIK the nilearn `Masker` doesn't do ROI-based extraction. But I'll double-check.

**Comment by tyarkoni** [comment]
Ah, I see, there's a hierarchy of them. Yep, that works. I'll just write a selector function that picks and initializes the right one.
