### ISSUE TITLE
masker handling

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#194]
There are some inconsistencies in masker handling across estimator classes that I think we need to resolve. Currently, only some estimators set a `.masker` property (e.g., the `IBMAEstimator` hierarchy). I think this is problematic, as it requires various checks in different places (I would like to avoid things like `hasattr(self, 'masker')`. I see no reason why there shouldn't always be a `.masker` attribute in every estimator class, which can be left to `None` if the user wants to use the masker defined in the `Dataset` instance. Any objection to my setting it up this way?

**Comment by tsalo** [comment]
I think that's reasonable to have for all Estimators.

**Comment by tsalo** [comment]
Would this be solved by just making the `IBMAEstimator` base class into a general `MetaEstimator` base class? The steps in IBMAEstimator seem pretty straightforward, and only minor changes would need to happen in the CBMA estimators' `__init__`s.

https://github.com/neurostuff/NiMARE/blob/96bec086c862dd6f3fefbc38dce22e3b2d4dc528/nimare/meta/ibma.py#L25-L40
