### ISSUE TITLE
IBMAEstimator class organization

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#196]
Probably a good time to talk about the organization of estimator classes. This applies to both CBMA and IBMA, but let's deal with IBMA first—I suspect there's more to talk about. Also tagging @nicholst and @cmaumet because this relates to the names/meaning of the estimators more than to the code architecture.

Currently we have the following IBMA estimators (some still in progress):
* Fisher's method
* Stouffer's z-score
* Weighted Stouffer's z
* Fixed effects (the canonical inverse-weighed method)
* Random effects (treats study as random, basically a t-test on studies)
* "fixed effects GLM" via FSL—I'm not sure how this differs from the canonical version
* "mixed effects GLM" via FSL—again I'm not sure what the difference is
* Mixed effects via Stan—gold standard, arbitrarily complex mixed-effects estimation

I may be missing something.

At minimum, I think we need to come up with more descriptive names for some of these. E.g., I don't like having `FFX` and `FFX_GLM` classes; this will be completely opaque to users. If the latter is specifically tied to FSL, we could maybe call it `FFX_FSL` (and ditto for `MFX_FSL`).

Alternatively, if the implementation differences are relatively minor, we could parameterize generic `FFX` and `MFX` classes with `method` and/or `estimator` arguments. So it would be somethiing like `est = FFX(method='fsl', ...). I think the choice here depends on just how different the internal model is, so it would be good to have input from Tom or Camille. It's also worth considering just getting rid of the FSL-based methods. I'm sure they do something slightly different, and possibly better, but the overhead is very high, and I'd prefer to encourage people to use standard, well-understood models. Is there any good reason to keep these around? 

Along similar lines, I see no reason to have separate `Stouffers` and `WeightedStouffers` methods/classes; IMO weights should just be an argument to `Stouffers`, much like the conventional fixed-effects models can take arbitrary weights, or weight by variance or sample size. We could even consider pushing Fisher's and Stouffer's into the `FixedEffects` class and specifying those via the `method` argument.

I guess my proposal is to consolidate/refactor into the following classes (I'm less concerned about the methods that the classes are wrapping):

* `Fishers` (maybe)
* `Stouffers` (maybe)
* `FixedEffects`
* `FSLFixedEffects` (maybe)
* `RandomEffects`
* `StanMixedEffects`
* `FSLMixedEffects` (maybe)

There is something pretty appealing to me about just having `FixedEffects`, `RandomEffects`, and `MixedEffects` classes, but that's probably pushing too hard in the direction of elegance, as the required inputs and arguments for some of the "methods" are likely to vary.

Thoughts?

**Comment by tsalo** [comment]
Personally, I would prefer to remove FSL as a dependency in the long run.

I don't have a strong opinion on the final set of classes. I think Tom and Camille's opinions are far more valuable on that topic, since I based our organization on theirs.

**Comment by nicholst** [comment]
Hi @tyarkoni @tsalo,

In order...

* Random effects (treats study as random, basically a t-test on studies)

Not sure what this is... a "t-test on studies" is actually no formal meta-analysis method, but one that @cmaumet evaluated.  

When, outside of imaging, someone says "Random effects meta-anlaysis" the generally mean the [DerSimonian and Laird](https://handbook-5-1.cochrane.org/chapter_9/9_4_3_1_random_effects_dersimonian_and_laird_method_for.htm), which just uses a dumb-as-dirt methods-of-moment estimate of the between subject random study variance (which may seem awful, but various papers have said, eh, not so bad [[1](http://dx.doi.org/10.1016/j.jspi.2009.09.017)], or can be improved if you use a more sensible sample variance & a t distribution [[2](http://www.ncbi.nlm.nih.gov/pubmed/24548571)]).

"mixed effects GLM" via FSL - So relative to DerSimonian and Laird, FSL is rocket science... i.e. it uses ML (essentially) to estimate the between study variance.  In the meta-analysis world, estimation with REML seems to be best practice (method "PM" in this great paper [1](http://doi.wiley.com/10.1002/jrsm.1164), and in fact that is the default in R's metafor package's linear mixed effect tool (`rma.uni`)).


So, to me, the complete list is:

* `Fishers`
* `Stouffers`
* `FixedEffects`
* `MixedEffects-DSL`
* `MixedEffects-FSL` or `MixedEffects-ML`
* `MixedEffects-REML`
* `MixedEffects-Stan`

Where -DSL is MoM estimation of between study variance, -ML & -FSL uses ML and -REML uses REML, which should be the best practice classical method.

As an aside, FSL's ML may be quirky, and so an independent implementation may find different values.  In particular, it is often common practice to allow random effects estimates of variance to go negative as long as the total variance (Fixed+Random) remains positive.  FSL rather forces the random effects variance to be positive, and has a bias as a result.

If the purpose is to replicate existing tools we'd need FSL, but honestly, I don't think it's important, and you could get away with *just* having mixed model methods:

* `MixedEffects-DSL`
* `MixedEffects-REML`
* `MixedEffects-Stan`

Where the DSL (MoM) is there as a fast, cheap and chearful method that has been used for years, REML is Classical best practice, and Stan is Bayesian best practice.

How does that sound?

**Comment by tyarkoni** [comment]
Thanks @nicholst!

I like the idea of sticking with fixed and mixed—I don't see any need for the t-test.

I think the straightforward thing to do here is to wrap StatsModels, which supports both REML and ML estimation of mixed-effects models. It does *not* implement the DerSimonian-Laird estimator, and I don't see a good reason to implement it. I believe the StatsModel implementation can currently only handle nested and not crossed random effects, but for meta-analysis purposes that's a pretty weak constraint. The Stan estimator will be able to support more complex GLMMs.

Given that ML/REML is just an argument to StatsModels, it doesn't seem sensible to have separate classes for this. My inclination is to start with a `MixedEffects` class that has a `method` argument with values `['reml', 'ml']`, and we can add additional estimators down the line. The Stan estimator is sufficiently different (because Bayesian, MCMC, takes way more arguments, and *slow*) that I think it should be its own class (maybe `BayesianMixedEffects`, as that's the most salient difference in terms of interpreting the results).

If we do *that*, then the question is whether we want to give the `FixedEffects` class the same treatment—i.e., we'd lose all the individual classes and just keep the one, with `method=['fe', 'stouffer', 'fisher']`. I lean towards no—I think a reasonable principle is to say that we introduce a new class any time the model specification itself differs in some important way, or requires different inputs, and add options to `method` any time it's just a different estimation procedure.

Does that all sound reasonable?

**Comment by nicholst** [comment]
I don't have the big picture on class structure, so I leave that to you, but on other points:

* Drop DerSimonian-Laird - Sure, agree... it's old technology.
* Fixed effects - Given that this does involve weighting, does it make sense to make it a special case of "MixedEffects", with argument `'fixed'`? 
* Are you sure that StatsModels will do the meta-analysis random effects as you think?  The meta-analysis case is pretty special, in that you *don't* re-estimate the first level variance, and just condition on it as provided.  In that way, it's very unlike a mixed model where you have cluster/repeated measure structure that lets you estimate the different variance components.

**Comment by nicholst** [comment]
One more follow up... a student I've worked with, Han Bossier @HBossier, has published a preprint on the best practice analysis of effect sizes [[1](https://www.biorxiv.org/content/10.1101/865881v1)].  The idea is that, aside from Fishers/Tippets, everything we're doing here assumes we have access to the effect estimates and standard errors; in practice, there are many settings (e.g. combining values from FSL and SPM) where you don't trust that the effect estimates have the same units, and so the only thing that is comparable are the standardised effect sizes, mu/sigma or (mu1-mu2)/sigma.  But, it turns out that sample standardised effect sizes are biased (if this seems mysterious, just note that the [noncentral t](https://en.wikipedia.org/wiki/Noncentral_t-distribution#Moments_of_the_noncentral_t-distribution), a multiple of the sample standardised effect size, has a bias for the noncentrality parameter that depends on true effect size and DF.

So!  I don't know if want to implement the results Han reviews with high priority, but I would give a think about how they will fit into your class structures.  

As a summary, the main changes that working with standardised effects sizes brings is:

1. A bias correction, especially important for small DF (see section 2.2 of Han's report)
1. Intra-study variances that are directly computed from the sample standardised effect size and DF, not from data analysis (see section 3.2.1)

@HBossier - Do you agree?! Have I missed anything?

**Comment by tyarkoni** [comment]
@nicholst yeah sorry, I meant to follow up on this yesterday and forgot. StatsModels does *not* support meta-analysis—it doesn't work with existing lower-level variance estimates. The `metafor` package in R does, and my implementation of the Stan mixed-effects wrapper does, but we're kind of stuck as far as SM goes.

 This sort of leaves us in a problematic position. We can have a Stan-based estimator that does more or less whatever we want, as those models are easy to write. But that's very slow (precludes voxel-wise analysis) and Bayesian (not that Bayesian is bad, just that people may not want it). AFAICT—and I spent some time googling—there is presently *no* Python implementation of any of the classical meta-analytic estimators.

In an ideal world, I think the right solution here would be to write a new Python package for generic meta-analysis (which would include an effect size conversion module, addressing your above concerns). That would probably be widely used well beyond the confines of this project. Then we would wrap that in NiMARE, adding only the imaging-specific stuff. This is sort of where I was already going with the existing architecture (the classes wrap functions that take arrays only, and never see any image-related data). But I don't trust myself to write passable ML/ReML random effects estimators. So I guess we're stuck with FSL–which I'm not entirely happy with. Thoughts?

**Comment by tyarkoni** [comment]
Okay, I pushed a prototype of a new [PyMARE](https://github.com/neurostuff/PyMARE) package that does domain-general mixed-effects meta-regression in Python. It currently supports  estimation using the WLS, ML, ReML, DerSimonian-Laird, and MCMC (in Stan) methods.

The API is similar to scikit-learn and NiMARE, but I made some internal implementation decisions that should make it easier to wrap efficiently (e.g., one can call directly into the estimation logic via each estimator's `._fit()` method rather than `.fit()`, which circumvents validation of input and construction of an output object).

Will give this some time to stabilize and mature, and then we can wrap it in NiMARE.

(As an aside, the name "PyMARE" may be a mistake: I'm already having to correct myself regularly when I mean to type NiMARE, or vice versa.)

**Comment by HBossier** [comment]
> One more follow up... a student I've worked with, Han Bossier @HBossier, has published a preprint on the best practice analysis of effect sizes [[1](https://www.biorxiv.org/content/10.1101/865881v1)]. The idea is that, aside from Fishers/Tippets, everything we're doing here assumes we have access to the effect estimates and standard errors; in practice, there are many settings (e.g. combining values from FSL and SPM) where you don't trust that the effect estimates have the same units, and so the only thing that is comparable are the standardised effect sizes, mu/sigma or (mu1-mu2)/sigma. But, it turns out that sample standardised effect sizes are biased (if this seems mysterious, just note that the [noncentral t](https://en.wikipedia.org/wiki/Noncentral_t-distribution#Moments_of_the_noncentral_t-distribution), a multiple of the sample standardised effect size, has a bias for the noncentrality parameter that depends on true effect size and DF.
> 
> So! I don't know if want to implement the results Han reviews with high priority, but I would give a think about how they will fit into your class structures.
> 
> As a summary, the main changes that working with standardised effects sizes brings is:
> 
>     1. A bias correction, especially important for small DF (see section 2.2 of Han's report)
> 
>     2. Intra-study variances that are directly computed from the sample standardised effect size and DF, not from data analysis (see section 3.2.1)
> 
> 
> @HBossier - Do you agree?! Have I missed anything?

Sorry for the delayed response, but yes I agree! And adding: there are multiple options to estimate between-study variability when working with standardized effect sizes. The popular DerSimonian & Laird has nicer alternatives such as a Hedges estimator (see also section 3.2.2 of [the paper](https://www.biorxiv.org/content/10.1101/865881v1.full.pdf).

**Comment by tyarkoni** [comment]
Hi @HBossier,

Thanks for the update. Now that the basic framework is in place, additional estimators should be fairly easy to add. I'll circle back to this at some point, but if you have some spare cycles and are comfortable in Python, feel free to take a look at [PyMARE](https://github.com/neurostuff/PyMARE), and particularly the estimators module [here](https://github.com/neurostuff/PyMARE/blob/master/pymare/estimators/estimators.py).

All the I/O handling is deliberately abstracted away, so adding a new estimator is as simple as implementing the new class's inner `_fit()` methods, which gives one automatic access to the estimates (`y`), variances (`v`), and any optional fixed covariates (`X`). As an example, see the [DerSimonian-Laird estimator](https://github.com/neurostuff/PyMARE/blob/c9e4d2ef5de198a5ce2e622fa8e342b694992896/pymare/estimators/estimators.py#L79) implementation.

**Comment by tsalo** [comment]
> But I don't trust myself to write passable ML/ReML random effects estimators. So I guess we're stuck with FSL–which I'm not entirely happy with. Thoughts?

Even though we're stuck with FSL for MFX_GLM, can we drop the FSL FFX_GLM estimator?

**Comment by tyarkoni** [comment]
We're no longer stuck with FSL for anything. :) I now trust myself to write passable ML/REML estimators (they're already in pymare). So we can drop all of the FSL estimators (I've started a branch that does that, and adds pymare functionality).

**Comment by tsalo** [comment]
Oh that's awesome! Never mind then.

**Comment by tsalo** [comment]
Now that #273 is merged in, I think most of the estimators are properly labeled. The only one that needs a better name is what I currently am calling `Something` (yes yes I know), which supports both `DerSimonianLaird` and `Hedges` PyMARE estimators, since they have the same requirements. Should I split those two into different IBMAEstimators or is there a better name for the combined one?

**Comment by tyarkoni** [comment]
Sorry, I'm just catching up now to issues that have been piling up from various repos. I agree that splitting was the right thing to do.

**Comment by tsalo** [comment]
I think the basic structure within NiMARE is in place (with the exception of the Stan estimator), and, as long as you're happy with that organization, the original purpose of this issue has been fulfilled. I'd like to close this issue, open one new issue in NiMARE for the Stan estimator, and open one more in PyMARE for @HBossier's bias correction method. Does that sound good?

**Comment by tsalo** [comment]
I opened neurostuff/PyMARE#48, so I'm going to close this now.
