### ISSUE TITLE
Use nilearn-style data directory for downloaded files

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#198]
Currently, we default to `nimare/resources/` for downloaded files, but that location (1) isn't very accessible if you install with pypi and (2) is located within the git repository if you're working on a fork (which means these files can be accidentally tracked and pushed).

I think it would be preferable to store those files (including MALLET and any trained models) in a more accessible folder, much like how nilearn and nltk do it. We can add relevant data_dir functions to `nimare.utils`, possibly just copied from nilearn.

**Comment by tyarkoni** [comment]
Makes sense to me. We can probably default to `~/.nimare`.

**Comment by tsalo** [comment]
Oh yeah that's where you set the test data to! I discovered I already had that folder and was very confused about how. Now I think it's just a matter of adding functions that use that path when downloading things outside of the tests.
