### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#21]
It might be nice to have a logo for NiMARE. Any ideas are welcome, but there are a few possibilities already brought up:
- A horse (as in [The Nightmare](https://en.wikipedia.org/wiki/The_Nightmare))
- A brain with tentacles and a face
- A hydra (great idea from @62442katieb)

**Comment by chrisfilo** [comment]
I love the project, but I have to say I'm a bit worried about the nagatie connotation regarding the name and how it will impact the logo. You don't want people to joke that this tool is a nightmare to use... Obviously it's up to you, but this is something to think of.

**Comment by tsalo** [comment]
That's fair. The logo can definitely lean more toward Monster's, Inc. than a Cronenberg movie.

**Comment by tyarkoni** [comment]
I think as long as we go cartoonish, something a bit sinister should be fine. Whatever the depicted object is, it would be cool if it could be composed entirely out of X/Y/Z coordinates. That might work well if we go with a Hydra--l'm picturing three necks, each labeled x, y, or z, and made up entirely out of numbers

**Comment by emdupre** [comment]
What about something with a "nightmare-esque" color palette (I immediately think the [ghost type pokemon](http://pokepalettes.com/#gengar)) ? Then the actual design could then be simpler, maybe even just concentric or overlapping circles-&mdash; would loosely remind me of coordinate based analyses.

**Comment by tsalo** [comment]
@puckr When you have the time, would you mind taking a crack at this?

**Comment by puckr** [comment]
@tsalo sounds good. How about a horse with fire mane? All in dark blues and purples. Since its a logo it would be a bit cartoony/ not very realistic.

**Comment by tsalo** [comment]
I think it would be good to have three or so rough ideas. A horse, a ghost (or something similar), and maybe one more?

**Comment by tsalo** [comment]
![spider_nimare](https://user-images.githubusercontent.com/8228902/51932727-b8f76680-23cd-11e9-9d1b-2fbeb5a64715.png)
