### ISSUE TITLE
Integrate PyMARE into image-based meta-analysis estimators

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#211]
Continues from https://github.com/neurostuff/PyMARE/issues/31#issuecomment-626407883.

@tyarkoni Do you want to get this merged before 0.0.2? I remembered that there's a big bug in 0.0.1 and now that it should be fairly easy to deploy releases, I was thinking it would be good to release 0.0.2 soonish.

**Comment by tyarkoni** [comment]
Your call, but I don't see a problem releasing 0.0.2 ASAP, and then 0.0.3 (or maybe even 0.1!) as soon as the IBMA stuff is ready, whether that's next week or 6 months from now. :)

**Comment by tsalo** [comment]
Okay thanks! I've added this issue to a 0.0.3 milestone. Feel free to rename that to 0.1 if you feel like that makes more sense.

I'm going to make a 0.0.2 release pretty much as soon as #209 is resolved, so that the latest stable release doesn't have those frustrating I/O bugs that are present in 0.0.1.

**Comment by tsalo** [comment]
Are your changes going to go into #163 or a different branch/PR?

**Comment by tyarkoni** [comment]
Different branch for sure. I think #163 will probably end up being abandoned (but let's leave it there for now just in case).
