### ISSUE TITLE
Rename "permutation" MCC method to "montecarlo"

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#215]
At the March Austin meeting, I recall someone mentioning that we should change the label "permutation" in our multiple comparisons correction module to "montecarlo", since that's the method we've actually implemented.

**Comment by tsalo** [comment]
Before I make this change, I just want to be sure that `montecarlo` is the desired name. @nicholst is that correct?

**Comment by nicholst** [comment]
Yes, that's the best description of it.
