### ISSUE TITLE
Add nimads module with classes that mirror the spec

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#218]
FYI @tsalo I've started working on a `nimads` module that provides lightweight data containers that mirror the spec and are backed by SQLAlchemy. The plan is to eventually split this out into its own package, which will interface directly with the central DB, as we've discussed in the past. But for now I'm just going to include it here, and then maybe rewrite the `Dataset` class so a lot of the `get()` methods operate over the `Study`, `Analysis`, etc. classes. This will make it easier to do lazy loading, study filtering, etc.

**Comment by tsalo** [comment]
@tyarkoni is there any chance your `nimads` module code is still around? I'm wondering if it might be good to try working from that instead of starting from scratch.

**Comment by tyarkoni** [comment]
IIRC I don't think I had a separate `nimads` module; what I had was built into the new Neurosynth back-end. I think @jdkent commented most of that code out, but it should still be in there. If you don't find anything that looks right, let me know, and I can check again.

**Comment by tsalo** [comment]
Thanks! I'll follow up with James then.

**Comment by jdkent** [comment]
ah, would this be the JSON-LD representation in neurostore?

Here is a commit with the original definitions:

https://github.com/neurostuff/neurostore/blob/26cd210a5ed6efbc7e8b761ff38dabfe95931524/neurostuff/schemas/schemas.py

**Comment by jdkent** [comment]
this has been completed with the nimad module in NiMARE
