### ISSUE TITLE
Improve handling of image spaces

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#229]
The Dataset currently can transform coordinates between different spaces, but no effort is made to check or transform between standard spaces for images. 

At minimum, we could:
- Document the limitation in the Dataset docstring
- Check affines and raise warnings when the affines don't match.
- Apply `resample_to_img` to deal with resolution differences between dataset images and the selected template.

I don't think actually warping images is a reasonable goal right now, but we should at least make that clear to users.

**Comment by tyarkoni** [comment]
I won't be able to respond much to NiMARE/PyMARE issues for the next ~2 weeks (busy with other time-sensitive things), but in general I like the idea of failing by default if there are mismatching spaces or affines, and hence forcing the user to explicitly take responsibility for this. Then they can indicate whether they want to use only the (shitty) transformation algorithms, or if they want to do (even shittier) resampling to the target template via `resample_to_image`. As long as failure is the default, I don't think anyone will be able to complain later that they didn't understand what was going on internally.

**Comment by tsalo** [comment]
Thanks for the heads up! I'm glad you like the idea though, and I will be able to move forward with it.

Also, I think that one option that we could point users toward is [templateflow/registration-framework](https://github.com/templateflow/registration-framework). I'm not involved with templateflow, but it looks like this repository's goal is to build and share transforms between common templates.

**Comment by tsalo** [comment]
Something I didn't realize about `nilearn` maskers is that they will handle resampling automatically, all on their own. Adding a warning or error would add a lot of overhead on NiMARE's side, because we would need to load every image and compare its affine to the `Dataset.masker`'s affine. At least for now, I'm going to document the limitations (i.e., images are assumed to be the same space, but may have different resolutions or affines) in the Dataset docstring.

**Comment by tyarkoni** [comment]
That's fine with me, though FWIW I think reading the affines adds very little overhead (the image data isn't read in, only the header, which is tiny).
