### ISSUE TITLE
Model storage

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#23]
A few of the tools that are going to go into NiMARE will require using trained models. In some cases, like GCLDA, NiMARE should provide the tools for training the model, but it may be time-consuming enough that users might want to just use pre-trained models that are saved somewhere. In other cases, like the CogPO classifiers from the ATHENA project, NiMARE won't be able to provide the training materials, because the raw data (i.e., labels and texts) won't be publicly available.

I am considering using figshare, but wasn't sure if there were any other resources that are better or are more commonly used in the field. Does anyone have any thoughts?

**Comment by tsalo** [comment]
I realized that @chrisfilo mentioned the OSF as a possibility for storage as well in #20. Depending on the API and on storage limits, that could be an option as well.

**Comment by tyarkoni** [comment]
How big are the trained models?

**Comment by chrisfilo** [comment]
Zenodo is another option - I used it for peaks2maps:
https://github.com/chrisfilo/peaks2maps/blob/master/peaks2maps/predict_from_checkpoint.py

Best,
Chris

**Comment by tsalo** [comment]
The largest model from the ATHENA project is 1.4 GB, but none of the other models from that project or from GCLDA seem to be quite that large.

I hadn't considered Zenodo, but I think that its dataset size limits and API could work well for our needs.
