### ISSUE TITLE
Clarification of varcope units

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#238]
I am currently taking a crack at #207 and I'm stuck on varcopes. I _know_ that someone (probably @nicholst) explained this to me somewhere, but I can't seem to find that conversation.

Just to explain what I _do_ know:
- Varcope is _not_ parameter estimate variance.
- According to the [FEAT User Guide](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FEAT/UserGuide):
    - `tstat = cope/sqrt(varcope)`
- In regression, `t = b / SE`
- `SE = sqrt(var / n)`

Does this mean that `varcope = var / n`?

**Comment by nicholst** [comment]
Hi @tsalo,

In fact, varcopes *are* the (estimated) variance of the parameter estimates.

Are you looking for the *population* variance?  In general, you can't know the population variance.  *If* you knew that a one-sample *non-mixed* effects model was used, then, sure,

```
est_pop_var = n * varcope
```

But otherwise we can't know it.

**Comment by tyarkoni** [comment]
To add to @nicholst's answer and directly answer your last question, yes, `varcope = var / n`.

The confusion (which I've also struggled with) stems from the fact that "sample varance" is used to refer to the variance of the individual observations (in a single sample), whereas "sampling variance" refers to the variance of the parameter estimate (i,e., what you'd get if you were to acquire repeated samples and take the mean of their squared deviation from the overall mean).

**Comment by tyarkoni** [comment]
The IBMA estimators can be passed the `varcope` data without modification; the "variances" referred to by pymare (and metafor) are sampl*ing* variances.

**Comment by tsalo** [comment]
Ah, thank you! I'll target sampling variance for the new variance-related transforms then.
