### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by chrisgorgo** [neurostuff/NiMARE#24]
When running https://github.com/neurostuff/NiMARE/blob/master/examples/nidm_pain_meta-analyses.ipynb I got the following error:

```
No such file: 'c:\gdrive\workspace\nimare\nimare\resources\templates/MNI152_2mm_mask.nii.gz'
```

Should those templates be added to the repo?

**Comment by tsalo** [comment]
Oh, actually in #15 I switched to using nilearn to grab the templates and masks (see [here](https://github.com/tsalo/NiMARE/blob/37c81797319f6f6c368be26a9117b574d071e887/nimare/utils/utils.py#L17)). I can move that into a smaller PR if need be.

**Comment by chrisfilo** [comment]
That would be great!

**Comment by tsalo** [comment]
I just opened #26 with new, nilearn-based `get_template` function.

**Comment by tsalo** [comment]
#26 is now merged. Is this good to close?
