### ISSUE TITLE
Include black formatting evaluation in style check

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#298]
I'd like to look into the [black code formatter GitHub Action](https://github.com/marketplace/actions/black-code-formatter). @akimbler is planning to test this out with his own repos, so we'll wait on what he has to say.

**Comment by akimbler** [comment]
I could see this working one of two ways

> We set up a Github Action to run black after each merge.
> We add `flake8-black` to the Style Checking and if it fails the person working on the PR should just run black and commit
