### ISSUE TITLE
Can't run ALE from CLI

### ISSUE THREAD

**Issue by albydnc** [neurostuff/NiMARE#309]
I have tried to do a simple ALE on a dataset from Sleuth.
The command I used is `nimare ale --output_dir ./ --n_iters 1000 --v_thr 0.001 --n_cores -1 ../neuro/Passive_listening.txt`
and I got this error:
```
INFO:nimare.workflows.ale:Loading coordinates...
Traceback (most recent call last):
  File "/home/albertoperro/anaconda3/envs/Sari/bin/nimare", line 8, in <module>
    sys.exit(_main())
  File "/home/albertoperro/anaconda3/envs/Sari/lib/python3.7/site-packages/nimare/cli.py", line 413, in _main
    options.func(**args)
  File "/home/albertoperro/anaconda3/envs/Sari/lib/python3.7/site-packages/nimare/workflows/ale.py", line 32, in ale_sleuth_workflow
    dset = convert_sleuth_to_dataset(sleuth_file, target='ale_2mm')
  File "/home/albertoperro/anaconda3/envs/Sari/lib/python3.7/site-packages/nimare/io.py", line 272, in convert_sleuth_to_dataset
    temp_dict = convert_sleuth_to_dict(text_file)
  File "/home/albertoperro/anaconda3/envs/Sari/lib/python3.7/site-packages/nimare/io.py", line 171, in convert_sleuth_to_dict
    ' ', '').replace('//Subjects=', ''))
ValueError: invalid literal for int() with base 10: '//ThivardL,2000:StationarySyntheticvs.SilentBaseline'
```
On GingerALE I got no problems running it.

**Comment by tsalo** [comment]
Thanks for the bug report @albydnc. We've attempted to make our converter as flexible as possible, but without top-down specifications on Sleuth outputs it's generally a matter of fixing each bug as it comes. I have a couple of questions:

1. What version of NiMARE are you using?

2. Would you be willing to share the text file? 

3. Did you compile the file yourself or was it generated by Sleuth?

**Comment by albydnc** [comment]
Hi @tsalo, thanks for the fast reply.
I am using the 0.0.3 version of NiMARE.
Here it is the txt, it was generated by Sleuth [Passive_listening.txt](https://github.com/neurostuff/NiMARE/files/5099065/Passive_listening.txt)

The query parameters were:
+ Context is Normal Mapping
+ Paradigm Class is Passive Listening
+ Activation is Activations Only

**Comment by tsalo** [comment]
Okay, that makes sense. It looks to me like individual contrasts from the same sample were combined, and Sleuth uses both contrast names in separate lines before the sample size. I _think_ recent improvements to our Sleuth conversion function by @62442katieb should work with this just fine. @62442katieb what do you think?

If Katie agrees, I'd recommend trying to re-run your meta-analysis with the current master branch.

**Comment by albydnc** [comment]
I've installed in a fresh environment (python 3.7.6 conda) the master branch version **0.0.3+22.g35580ec**. Re-ran the meta-analysis and got same result as before.
```python
(testing) albertoperro@AlbertoWS:~/testing$ nimare ale --output_dir ./ --n_iters 1000 --v_thr 0.001 --n_cores -1 ../neuro/Passive_listening.txt 
/home/albertoperro/anaconda3/envs/testing/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/albertoperro/anaconda3/envs/testing/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
INFO:nimare.workflows.ale:Loading coordinates...
Traceback (most recent call last):
  File "/home/albertoperro/anaconda3/envs/testing/bin/nimare", line 8, in <module>
    sys.exit(_main())
  File "/home/albertoperro/anaconda3/envs/testing/lib/python3.7/site-packages/nimare/cli.py", line 393, in _main
    options.func(**args)
  File "/home/albertoperro/anaconda3/envs/testing/lib/python3.7/site-packages/nimare/workflows/ale.py", line 39, in ale_sleuth_workflow
    dset = convert_sleuth_to_dataset(sleuth_file, target="ale_2mm")
  File "/home/albertoperro/anaconda3/envs/testing/lib/python3.7/site-packages/nimare/io.py", line 290, in convert_sleuth_to_dataset
    temp_dict = convert_sleuth_to_dict(text_file)
  File "/home/albertoperro/anaconda3/envs/testing/lib/python3.7/site-packages/nimare/io.py", line 182, in convert_sleuth_to_dict
    sample_size = int(exp_data[n_idx].replace(" ", "").replace("//Subjects=", ""))
ValueError: invalid literal for int() with base 10: '//ThivardL,2000:StationarySyntheticvs.SilentBaseline'
```

**Comment by tsalo** [comment]
That's unfortunate. I just opened #310, though, which should fix the issue. Once tests pass, I will merge that PR. I won't autoclose the issue though, so please try re-running on master once the PR is merged and let me know if it fixes the problem for you.

**Comment by albydnc** [comment]
Thank you, this way it worked.
I've tried to open it in Mango and it shows up but it says that is a 64 bit image and some data is lost.
By overlaying the same analysis done in GingerALE, the result are much different.
Is there some room for improvement? Am I doing it wrong?

**Comment by tsalo** [comment]
Can you give a bit more information about what you compared? To better narrow it down, here are a couple of questions and one recommendation:

- What were the GingerALE settings?
- Which map from each tool did you overlay?
- For a proper FWE correction I'd use 10000 iterations, not 1000.

**Comment by tsalo** [comment]
@albydnc I just wanted to follow up. Are you still concerned about differences between the NiMARE and GingerALE results?

**Comment by tsalo** [comment]
@albydnc I'm going to close this for now. Please feel free to reopen it if the problem persists.
