### ISSUE TITLE
Zenodo

### ISSUE THREAD

**Issue by chrisfilo** [neurostuff/NiMARE#31]
- [ ] Add NiMARE to Zenodo
- [ ] Enable github integration
- [x] Add `.zenodo.json`
- [x] Include information about `.zenodo.json` to PR template and contributors guidelines

**Comment by tsalo** [comment]
I still can't add NiMARE to Zenodo for some reason. Someone else will have to do that, but I've added the Zenodo file and PR template to the repo.

**Comment by tsalo** [comment]
Thanks for authorizing Zenodo @chrisfilo. Closing this now.
