### ISSUE TITLE
Test combinations of kernels and CBMA estimators

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#344]
The way we've set up the API is designed to allow users to combine kernel transformers and meta-analytic estimators in non-traditional ways. However, to this point I haven't actually tested that out. It would be worth it to include either tests or examples that combine kernels and estimators in different ways. Even if we find that some combinations raise errors (e.g., due to combining `int` MA maps from a KDA kernel with methods requiring `floats` in ALE), it would be worth it just to know what those combinations are.

**Comment by tsalo** [comment]
Tagging this as a GFI since it would involve minimal adjustments to existing tests, possibly moved into a new example.

**Comment by koudyk** [comment]
I'm working on this. I basically copied the [plot_cmba.py](https://github.com/koudyk/NiMARE/blob/master/examples/02_meta-analyses/plot_cbma.py) file, and then for each estimator I loop through the different kernels and visualize the results.

Is this what you had in mind?

**Comment by tyarkoni** [comment]
Looping @jdkent into the conversation, as this might also be relevant to what he's putting together.

**Comment by tsalo** [comment]
@koudyk that fits in with what I was thinking quite nicely! @jdkent might have additional insight (e.g., leveraging the new simulation module) though.

**Comment by koudyk** [comment]
Great, thanks! I'm a bit new to contributing. Should I do a pull request now to share what I've done, or wait to see what @jdkent says?

**Comment by tsalo** [comment]
If the code is ready, then please open a draft PR so we can see what it looks like. I'll just hold off on reviewing it until @jdkent has had a chance to weigh in.

**Comment by tyarkoni** [comment]
I haven't taken a look at #343 yet (hopefully will get to that today), but one thought would be to wrap @koudyk's code in a test and include it in the `nimare/tests/test_estimator_performance.py` module @jdkent created. I.e., in addition to testing on real data, we could apply all of the same kernel/estimator combinations to the fake data @jdkent is producing. (Though we would probably also want to keep a version tests that operate on the real data as well.)

Or we could just keep them separate for now. I'm fine either way.
