### ISSUE TITLE
Opt-in coauthorship on NiMARE manuscript

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#356]
Hello everyone. I am in the process of writing a manuscript about NiMARE, for submission to Aperture. The manuscript is nearly ready for coauthor input, and at this stage I would like to invite everyone who is registered in the package Zenodo file to be a coauthor. This is, of course, opt-in, in that I will not assume that anyone wants to be included without their explicit approval.

I am going to use this issue to keep track of the invited coauthors and their responses. If you would like to be included as a coauthor, please respond to this issue with your contact info so that I can give you permissions to the manuscript's Google Doc (or email me the info directly at `tsalo006@fiu.edu` if you're not comfortable posting it here). If you would not, you can respond with a comment to that effect, directly email me about it, or even just add a :-1: to this post.

I will close this issue in one week, on **October 26th**. I will try to follow up with folks who don't respond within that time frame, but I can't guarantee that I will be able to contact you via other means, so you may end up being left off the author list in that situation.

Zenodo contributors:

- [x] @tsalo 
- [x] @tyarkoni 
- [x] @nicholst
- [x] @jdkent 
- [x] @eglerean 
- [x] @62442katieb 
- [x] @bilgelm 
- [x] @jbpoline
- [x] @djarecka
- [x] @koudyk
- [x] @puckr 
- [x] @akimbler 
- [x] @Shotgunosine 
- [x] @julio-a-yanes
- [x] @alexprz 
- [x] @angielaird 

No response:
- [ ] @JesseyWright

Opted out:

- [x] @chrisgorgo (passed)
- [x] @yifan0330 (acknowledgement instead of authorship)
- [x] @jeromedockes (acknowledgement instead of authorship)

**Comment by eglerean** [comment]
Thanks for asking @tsalo! I just tested the code and fixed a broken path, not sure if that’s enough for a coauthorship in my standards. 😀 Can I opt-in and be in the coathors only if I can really help with the manuscript? (And eventually opt-out later if I realise I haven’t contributed much?). Great job anyway, so glad to see NiMARE going to Aperture.

**Comment by tsalo** [comment]
I am comfortable following fMRIPrep's model of including folks who made valid contributions regardless of how substantial they are, but I'm happy to follow your criteria. If, after reviewing the manuscript, you don't feel like you were able to contribute much, I can remove you at your request. If that does happen, I hope I could at least mention you in the Acknowledgements?

In any case, since you're willing to give it a try, would you mind sending me your email and maybe opening a PR to fill out your Zenodo entry? At minimum, it would be great to have your ORCID (if you have one).

**Comment by jeromedockes** [comment]
Hello Taylor, thank you for your kind offer. As I have not contributed
to NiMARE nor edited the paper I don't think I should qualify for
co-authorship.

If you think it is useful I am glad to do another pass of comments on
the paper; is the current version still in the google docs you sent
before?

**Comment by tsalo** [comment]
@jeromedockes That's fair. I would like to at least mention you in the acknowledgements, since your manuscript comments were very helpful in situating NiMARE's functional decoding approaches in the larger collection of methods out there. The manuscript is still in the same Doc, and will be until all coauthors have signed off on it.
