### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#36]
In order to incentivize use and contributions from developers of new methods, we'll want to generate some kind of boilerplate with citations beyond what duecredit would create.

**Comment by tsalo** [comment]
We will implement the boilerplate in the command line tool.

**Comment by tsalo** [comment]
Should we write out a boilerplate text file to the output directory or print the boilerplate to the terminal?

**Comment by tyarkoni** [comment]
I vote for the latter—text sent to stdout can always be piped to a file.

**Comment by tsalo** [comment]
Okay, that should be easy enough with logging (per #58).
