### ISSUE TITLE
LDAModel does not drop studies without texts

### ISSUE THREAD

**Issue by JulioAPeraza** [neurostuff/NiMARE#366]
If MALLET is setup (`model = annotate.lda.LDAModel(dset_abstract.texts, text_column='abstract', n_topics=200)`) with a `dset_abstract.texts` with at least one study without the abstract, the function will give the error:

```
Traceback (most recent call last):
  File "generate_cog-atlas.py", line 101, in <module>
    model = annotate.lda.LDAModel(dset_abstract.texts, text_column='abstract', n_topics=200)
  File "/opt/anaconda3/lib/python3.8/site-packages/nimare/annotate/lda.py", line 103, in __init__
    fo.write(text)
TypeError: write() argument must be str, not float
```

This currently happens for study [ 9728909 ](https://pubmed.ncbi.nlm.nih.gov/9728909/) and [20685394](https://pubmed.ncbi.nlm.nih.gov/20677377/) from Neurosynth (abstract for 9728909 is not available, and 20685394 was deleted because is a duplicated of 20677377).

**Comment by tsalo** [comment]
We can use the same approach as in `nimare.annotate.text.generate_counts()` to reduce the text DataFrame:

https://github.com/neurostuff/NiMARE/blob/a464778b10d86857f14c85c8e5cdf26b8063335b/nimare/annotate/text.py#L33-L40

**Comment by tsalo** [comment]
@JulioAPeraza do you have the time to implement this?
