### ISSUE TITLE
Peaks2Maps downloads model every time tests are run

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#367]
Haven't looked into the cause, but despite the "this is a one-off operation" message, the full (large) Peaks2Maps model seems to download every time I run the tests. Not sure if this is by design, but I think it's reasonable for the tests to keep the model around in this case; it adds a minute or so to the test run time.

**Comment by tsalo** [comment]
The test is downloading to a temporary directory instead of the NiMARE resources folder. We can drop the `tmp_path_factory` from that test, after which it should resolve to the same location and skip the download step.
