### ISSUE TITLE
Implement analytical null in KDA and MKDA estimators

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#370]
ALE's analytical null _should_ be applicable to other density-based methods. The basic approach is this:

1. Define histogram ranging from zero to maximum possible summary value (e.g., ALE or OF) for dataset.
    - This should be easy for MKDA, but could be very difficult for KDA. Also, we'll need to incorporate the weights that KDA and MKDA can support.
1. Calculate MA array for dataset.
1. Calculate summary value array for dataset.
1. Bin observed MA values in study-specific histograms.
    - (Zeros are counted separately due to Python's histogram code being terrible).
1. Looping through the studies, build a summary value histogram by convolving each study's MA histogram with the summary value histogram.
    - If that's not clear, just remember that the summary value histogram is set at first to the first study's MA histogram.
1. Convert summary value histogram into null distribution by normalizing the histogram and then calculating the cumulative sum.

**Comment by tsalo** [comment]
The hard part here, I think, is getting this working for KDA. In ALE and MKDA, the max possible MA value for each study is present in the study's MA map. However, since KDA sums MA values across foci, the max possible MA value is equivalent to the number of foci in the study times whatever the fill value is. Neither of these can be inferred from the MA map, which means that, if we want KDA to work with this approach, the method that produces the analytic null will need access to more information, such as the original coordinates. I'm not sure there's a clean way to do that.

**Comment by tyarkoni** [comment]
Good point. IMO this is yet another reason to just drop support for KDA. I find it pretty hard to think of a use case that would justify it. AFAIK we don't let people do old-school fixed-effects ALE analyses, so I don't know that we need to keep KDA around either...

**Comment by angielaird** [comment]
+1 for dropping KDA support

**Comment by tyarkoni** [comment]
@tsalo are you currently working on this? If not, I don't mind taking a stab at it. I'm running into some issues related to #360 after my changes in #374, and rather than revert, I think it makes more sense to deal with this issue first, as the refactoring will I suspect solve some of the other problems for free. If you're already working on this, no worries.
