### ISSUE TITLE
Move CBMA summary statistic calculation from Estimator to KernelTransformer

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#373]
Per today's call, building a generic CBMADensityEstimator will require access to the summary statistic calculation step based on the kernel, rather than the estimator. As such, we should move that function (let's call it `_compute_summarystat()` for now) from the Estimator classes to the KernelTransformer classes.

**Comment by tsalo** [comment]
This will have to happen _after_ #377 is handled.

**Comment by tyarkoni** [comment]
Given that we're keeping the separate `ALE` and `MKDADensity` classes, and some of the class methods will have very different implementations (e.g., `_compute_null_analytic`), there's probably no longer a good reason to move this to the kernel, so I vote we close it.

**Comment by tyarkoni** [comment]
@tsalo just tagging you here to make sure you see my edit to the previous comment. The residual point being that maybe we should abandon the "freely mix and match kernels and estimators" idea and restrict to only certain legal combinations inside each estimator.
