### ISSUE TITLE
Remove KDA Estimator

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#376]
Do we also want to remove the KernelTransformer? With the reorganization planned in #373, the whole algorithm will be stored in the kernel anyway.

**Comment by tyarkoni** [comment]
I'm inclined to say yes, but I also think we should keep it for the time being. The rationale is that, even if we don't want to keep KDA around long-term, I like the fact that it will force us to come up with a more generic way of handling the different algorithms. So let's keep it for now, make sure we can write something that could in principle handle the peculiarities of KDA (e.g., values > 1), and then we can remove it.

**Comment by tsalo** [comment]
Okay, that sounds good to me- especially since we don't have a NiMARE version of SDM, which we _do_ want. That means that we'll want a working version of the analytic null distribution for the KDA estimator though, so I guess I closed #370 prematurely. I will update that closed issue name/description and open a new one for KDA specifically.

**Comment by tsalo** [comment]
Closing this now that we have warnings for KDA and have implemented the analytic null.
