### ISSUE TITLE
ALE estimator with null_method=empirical and FWE=montecarlo is noticeably slower

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#384]
Haven't taken a look at the code yet, but the combination of the ALE estimator with the empirical null_method with the fwe montecarlo corrector performs slowly, (the first couple FWE montecarlo iterations take somewhere between 10-20 seconds and the following iterations take 2-5 seconds each).

This is impacting #380 to finish tests within the default timeout period of 10 minutes with no output.

**Comment by tyarkoni** [comment]
I've vectorized the empirical null generation methods for both ALE and MKDA, so that should help a bit. Am working on optimizing the monte carlo routines as well, so hopefully they'll be much faster soon.

**Comment by tyarkoni** [comment]
Update: #386 oesn't seem to have helped; tests are still stalling on Circle.

**Comment by tyarkoni** [comment]
Possibly related: things seem to stall (at least on my machine) with FWE=montecarlo and n_cores > 1. Seems like there might be some underlying multiprocessing issue.

**Comment by tsalo** [comment]
We've done a lot to the CBMA estimators and FWE correction. I wonder if this is still applicable.

**Comment by jdkent** [comment]
I don't think this is still applicable, I'll close.
