### ISSUE TITLE
Replace existing "empirical" generation of uncorrected p-values with full-blown coordinate shuffling

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#389]
For ALE and MKDA, we now have both analytical and permutation-based procedures for assigning uncorrected p-values to voxels. However, both methods are conservative, in that they assume voxels are independent, which is not true in practice. I.e., the current empirical permutation approach (which asymptotically converges with the analytical approach) randomly samples a single voxel from each study repeatedly, and builds up a null distribution by repeating the procedure many times. This overestimates the number of truly independent observations, and hence produces conservative correction thresholds (or uncorrected p-values).

We already support p-value generation based on actual shuffling of coordinates in the `FWECorrector`, so the proposal here is really just to provide the option to extract uncorrected p-values that way too. And since the current "empirical" approach is basically inferior to the analytical approach in all respects, we can probably just drop it entirely in favor of the full-blown coordinate shuffling. (I would probably keep these methods around but undocumented; for one thing, they're very helpful in ensuring that the analytical procedures are working as expected, as we can easily test for convergence.)

Probably we should rename the options too, as "empirical" is a bit confusing, IMO. I would suggest calling them "approximate" and "montecarlo", which would intuitively convey to users both that (a) the "approximate" approach doesn't really give the 'correct' answer (because it's biased by the independence assumption), and (b) the "montecarlo" approach is based on resampling and is likely to take a long time. Then the docs could more explicitly lay out the tradeoff, taking pain to emphasize that the "approximate" approach is actually conservative, so if you're willing to accept reduced sensitivity, it makes sense to just always use that.

[EDIT: One other minor issue: our current coordinate shuffling procedures don't take into account spatial relationships *within* a study. I.e., if two peaks overlap in the observed data, the probability of their overlap in any permutation is no greater than two peaks selected at random. I gather the reference implementation of MKDA accounts for the spatial structure in the resampling process, though I'm not sure exactly how that's done. We may want to explore this and do the same thing in NiMARE at some point.]

**Comment by tsalo** [comment]
So this issue has two proposals, right? The first is a simple terminology change. `empirical` becomes `montecarlo` and `analytic` becomes `approximate`.

> We already support p-value generation based on actual shuffling of coordinates in the FWECorrector, so the proposal here is really just to provide the option to extract uncorrected p-values that way too.

I'm not really sure what you mean by "shuffling" of coordinates. In the `montecarlo` FWE correction method, the coordinates are randomly drawn from the mask, although the number of foci per study is retained. In the uncorrected null distribution method, the coordinates are still randomly drawn from the mask, but only one coordinate per study is used. The original foci aren't shuffled in the sense of being reassigned across studies, or anything.

Is your proposal for the empirical null to randomly draw coordinates from the mask, but collect as many foci per study as were in the original study, as in the FWE correction? Then, to get an _uncorrected_ p-value, we'd need to retain the full distribution of ALE values in the null distribution instead of the maximum value, right?

> One other minor issue: our current coordinate shuffling procedures don't take into account spatial relationships within a study.

Would this be something like calculating distance between each pair of foci in the study and then randomly sampling foci that have the same distances?

**Comment by tyarkoni** [comment]
> So this issue has two proposals, right? The first is a simple terminology change. empirical becomes montecarlo and analytic becomes approximate.

Yep.

> Is your proposal for the empirical null to randomly draw coordinates from the mask, but collect as many foci per study as were in the original study, as in the FWE correction? Then, to get an uncorrected p-value, we'd need to retain the full distribution of ALE values in the null distribution instead of the maximum value, right?

Yes, that's right. It's basically the same procedure as what we're currently calling FWE correction (and we would probably want to abstract it out and then call it when using FWE correction), except retaining all values, rather than just the max. In the event this takes up too much memory (which seems likely for more than, e.g., a couple thousand permutations), we could explore various compression schemes (starting with histograms again).

> Would this be something like calculating distance between each pair of foci in the study and then randomly sampling foci that have the same distances?

Exactly, but there needs to be some reasonably efficient algorithm for it. And probably also some constraints on what peaks are considered close enough for the geometry to be preserved (otherwise we're just talking about a rotation of a fixed set of peaks through the brain volume, which would be severely limiting given that they presumably all need to end up in gray matter).

**Comment by tsalo** [comment]
If the coordinate shuffling-based empirical nulls are more different from the analytic nulls than the current version, does that mean we'll need to revise the analytic null methods?

**Comment by tyarkoni** [comment]
We can't; there's no straightforward way to take the spatial characteristics of the maps into account with the analytical method. The two will definitely give different results, but hopefully not by a lot, and in any case the analytical approach (as well as the permutation-based approach that assumes voxel independence) is overly conservative, so it's not a huge issue. I think we just present this to the user as a choice between a fast-but-slightly-conservative correction approach and a slow-but-properly-calibrated approach.
