### ISSUE TITLE
Improve convergence between ALE analytic and empirical null methods

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#396]
ALE analytic method converges with empirical  more when:
```
step_size = 0.00001
hist_bins = np.round(np.arange(0, max_poss_ale + 0.001, step_size), 5)
```
the ale analytic & empirical correlation is: 0.9999446144830378

Here's the false positive rates:
![image](https://user-images.githubusercontent.com/12564882/99124667-39e61900-25c8-11eb-9a92-c0b6e244e811.png)

the p-value distribution:
![image](https://user-images.githubusercontent.com/12564882/99124890-a103cd80-25c8-11eb-9931-89a248ef2042.png)

p-value correlation:
![image](https://user-images.githubusercontent.com/12564882/99125023-e6c09600-25c8-11eb-95f4-bce6e2a92088.png)

So increasing the granularity of the hist_bins by 10x for ALE appears to bring the analytic and empirical methods really close to each other (but this may bite into the performance gains that Tal has been working on)

_Originally posted by @jdkent in https://github.com/neurostuff/NiMARE/issues/383#issuecomment-727057249_

**Comment by tsalo** [comment]
Huge +1 to this. I'd like to see a basic speed check (not even a full profile, just `%%time` in a notebook would be enough), but I think this is a very good idea. It's also very easy to implement, so I've labeled it as a GFI.

**Comment by tyarkoni** [comment]
Agreed, this is great! And I second the suggestion to add basic timing info. This won't be for purposes of development/optimization (which is easy to do in a more systematic way with something like [pytest-profiling](https://pypi.org/project/pytest-profiling/), but more to give end users a basic sense of how long they can expect a typical analysis to take.

**Comment by tsalo** [comment]
@jdkent do you want to open a PR with the enhancement? Otherwise, I can do it.

I think we can leave the performance check for #383.

**Comment by tsalo** [comment]
In my fork, I leveraged `n_iters` to define the resolution of the histogram bins:

```python
# Determine bins for null distribution histogram
max_ma_values = np.max(ma_values, axis=1)
max_poss_ale = self.compute_summarystat(max_ma_values)
step_size = 1 / self.n_iters
level = int(np.ceil(-np.log10(step_size)))  # number of decimal points to round to
hist_bins = np.round(np.arange(0, max_poss_ale + (step_size * 100), step_size), level)
self.null_distributions_["histogram_bins"] = hist_bins
```

and then ran a quick time profile in a notebook:

![image](https://user-images.githubusercontent.com/8228902/100519902-d67fed80-3168-11eb-8f5f-762328287ac1.png)

The general finding is that the higher-resolution analytic null takes 3X as long, but the change is negligible compared to the time the empirical null or Monte Carlo FWE correction takes, so IMO the effect on time is really not a problem. I will open a PR with 100000 bins hardcoded in, rather than the above approach.
