### ISSUE TITLE
Support for image only dataset?

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#405]
In creating simulated image datasets, it appears there is an expectation that [at least one study/contrast contains coordinates](https://github.com/neurostuff/NiMARE/blob/8dc6c55680c4eece74917b7d8802501e1cae0b4c/nimare/utils.py#L66-L104), since one cannot [concatenate](https://github.com/neurostuff/NiMARE/blob/8dc6c55680c4eece74917b7d8802501e1cae0b4c/nimare/utils.py#L106) 0 dataframes ([an empty list](https://github.com/neurostuff/NiMARE/blob/8dc6c55680c4eece74917b7d8802501e1cae0b4c/nimare/utils.py#L66)). If I'm only using the image-based meta-analysis estimators, is it necessary to have coordinates reported?

**Comment by tyarkoni** [comment]
We definitely shouldn't require coordinates, so marking this as a bug.
