### ISSUE TITLE
Many IBMA estimators have extra dimension on output

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#449]
## Summary

All of the pymare based meta-estimators and permuted-ols have an extra dimension on the statistical map output

## Additional details

- NiMARE version: 0.0.7

### What were you trying to do?
work with ibma statistical map output

### What did you expect to happen?
res.get_map("z").ndim == 3

### What actually happened?
res.get_map("z").ndim == 4

## Reproducing the bug

Run this test and check the dimensionality of the output.
https://github.com/neurostuff/NiMARE/blob/713a231527b3d4615a86161bcf174e0a52c96752/nimare/tests/test_meta_ibma.py#L50-L55

**Comment by tsalo** [comment]
Is this a bug on NiMARE's end or PyMARE's?

**Comment by jdkent** [comment]
It could be on PyMARE's end if that behavior is unexpected, I do not know if there is supposed to be support for multivariate/multiple regression in PyMARE and having a single response/dependent variable is a special case.

**Comment by tsalo** [comment]
I think you're right to solve it on our end, but we may want to follow up in PyMARE as well.
