### ISSUE TITLE
Passing certain maskers (e.g., NiftiLabelsMasker) will produce invalid results for IBMA estimators

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#466]
## Summary
Currently I believe we let users pass any nilearn `Masker` in at estimator initialization, and then internally use that masker to reduce the data. This works fine for certain estimators, but will lead to wonky/invalid inferences in other cases.

## Additional details
Consider any of the PyMARE-based IBMA estimators that expect the input to be pairs of estimate and variance maps. Suppose the user passes a `NiftiLabelsMasker` as the mask. Then the expectation is presumably that the meta-analysis will be done separately for each discretely-labeled ROI in the mask. Naively, the masker will reduce the dataset by averaging over all voxels within each ROI—and it will do this (I think) for both the parameter estimate and the sampling variance maps. The former is not a problem, but the latter is problematic because (a) we need to scale the variance by the number of voxels in the ROI (which we could do ourselves, but it would be an extra step), and (b) voxels are dependent, and we have no idea what the covariance matrix looks like (nor any good way to estimate it). The net effect is that the variances being passed to PyMARE internally will be (heavily) biased, and hence so will p/z-values. (Credit to @nicholst for pointing this out in email a while ago.)

A related problem will arise for the combination tests (e.g., Fisher's or Stouffer's): I presume the naively applied masker will average z-scores within ROIs, but this is not at all what we want—we presumably would need to aggregate values within each ROI via some Fisher's-like procedure (but not using any of the methods currently in PyMARE, because they all assume independence).

## Reproducing the bug
Almost any ROI-based IBMA analysis will suffer from this issue. The exceptions are the estimators that take parameter estimates but not variances as inputs (I think that's currently only the `SampleSizeBasedLikelihood` estimator, which frankly is kind of crappy).

## Proposed solution
Disable ROI-based analyses entirely in the package until we can figure out a sensible solution to the problem (which is going to be... hard). Masking is fine so long as the user's just defining the valid voxel space, but as soon as there's aggregation of voxels, all bets are off.

**Comment by jdkent** [comment]
@tyarkoni, do you have that email/could you paste it here? I would like to read more about the issue to understand it better.

**Comment by tyarkoni** [comment]
> This is a little depressing 😞(especially for the NiMARE paper) but on the bright side we can probably handle this fairly easily by checking the mask type in get_masker.

Yeah, it's a bummer.

This might be a good impetus to bring back the old "GLM" approach, which was basically just a t-test on the averaged estimates. That's equivalent to using `WeightedLeastSquares` with unit variances everywhere, so it wouldn't require any PyMARE changes; we could just re-use the code in NiMARE's `WeightedLeastSquares.fit()` with `v=None` in the PyMARE dataset. We could probably just call it `LeastSquares`. This would at least provide a valid and widely understood way to do ROI-level tests, even if performance is probably not great.

> @tyarkoni, do you have that email/could you paste it here? I would like to read more about the issue to understand it better.

No, because it's a long thread with lots of in-line comments, but here are a couple of stats/math exchange threads giving more succinct explanations: [1](https://stats.stackexchange.com/questions/31177/does-the-variance-of-a-sum-equal-the-sum-of-the-variances), [2](https://math.stackexchange.com/questions/115518/determining-variance-from-sum-of-two-random-correlated-variables).

**Comment by nicholst** [comment]
The only quick and dirty solution I can think of is using a simple mixed model with random intercept per subject to the ROI-level data.  The estimated mean (the population intercept, over subjects and ROI values) will be the outcome of interest and we can easily get the estimate and standard errors.

This is not exactly the 'right' model, as it will only capure compound symmetry correlation within each ROI (i.e. each voxel in the ROI equally correlated with each other), but will be a big step towards the highly biased SE from the naive approach.  Slightly more nuianced models could use a few spatial bases (e.g. linear trends, or tensor spline bases) as random factors which would account for more spatial structure in the ROIs.

**Comment by tsalo** [comment]
Between this thread and conversations on Slack, it seems like the current easy solution is the following:

1. Prohibit non-NiftiMasker maskers for combination tests (Fishers and Stouffers).
2. Log a warning about biased variance for non-NiftiMasker maskers for non-combination, non-likelihood tests (Hedges, WeightedLeastSquares, and DerSimonianLaird).
3. Log a warning for likelihood-based tests (SampleSizeBasedLikelihood and VarianceBasedLikelihood).
     - This is separate because I think we are less certain about how averaging will impact these ones. Is that correct?
4. Leave PermutedOLS alone.
     - PermutedOLS just uses the contrast maps, so it should be fine, right?

Does that sound like a reasonable next step, pending progress in #475 or new estimators for the methods proposed by @nicholst?

**Comment by tyarkoni** [comment]
I think that's right, except:
* The `SampleSizeBasedLikelihood` should be just fine, as it doesn't depend on the variances at all, and the sample size is a constant for each study. (It will still be a shitty estimator that people should avoid if they can use one of the variance-using estimators, but that's true whether or not one is doing ROI analyses.)
* We can probably give the same warning for all the estimators that depend on the variance; I'm sure they will each behave slightly differently, but I don't think we're in a position to say exactly how, absent a much more systematic analysis. It should be something that makes the user nervous but doesn't induce outright panic. Maybe something like "Note that the aggregation of variance estimates within ROIs can introduce bias and/or variance to the results. Preliminary analysis and simulation suggests the effect is likely to be small in most cases, but no guarantees are provided, and users are encouraged to conduct analyses at a whole-brain level when feasible."

**Comment by nicholst** [comment]
Agree with your plan @tsalo as amended by @tyarkoni
