### ISSUE TITLE
Split logging between stdout and stderr depending on message level

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#482]
## Summary

In running analyses for the NiMARE manuscript ([`NBCLab/nimare-paper`](https://github.com/NBCLab/nimare-paper)), I've noticed that the stderr outputs from SLURM are overly cluttered because `logging` defaults to stderr. It would be great to send INFO/DEBUG messages to stdout and WARNING/ERROR messages to stderr.

## Additional details

This wouldn't impact most folks, but would be useful in debugging with a job scheduler.

## Next steps

1. Use two `StreamHandlers` (one for stdout and one for stderr) with a `Filter` that filters messages based on a level threshold.
2. Add the handlers to `nimare/__init__.py`, I think.
3. Add the handlers to the basic config for NiMARE.

**Comment by tsalo** [comment]
@jdkent do you have a strong opinion one way or the other on this?

**Comment by jdkent** [comment]
No strong preference, my main question is how useful the INFO/DEBUG messages are in this context. If INFO/DEBUG messages are not very useful, then raising the logging level should be a good solution so you only get WARNING/ERROR, but if INFO/DEBUG statements are still useful, then I see the motivation for splitting the messages up.

Another thought is the order of the messages, if they are all in stderr it is easier to discern what order the INFO/DEBUG/WARNING/ERROR were encountered if that is important.

**Comment by tsalo** [comment]
Hm... that's a fair point. We could probably just increase the default logging level.

> Another thought is the order of the messages, if they are all in stderr it is easier to discern what order the INFO/DEBUG/WARNING/ERROR were encountered if that is important.

That's a good point too. Okay, I'm going to close this, and if I circle back at some point and think it's worth revisiting, I'll reopen. Thanks for your thoughts!
