### ISSUE TITLE
Start using `versionadded` and `versionupdated` directives in docstrings

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#489]
## Summary

I would like to use [Sphinx decorators (or directives)](https://deprecated.readthedocs.io/en/latest/sphinx_deco.html) in docstrings to indicate the NiMARE version in which the item was added or last meaningfully changed.

## Additional details

This will help users keep track of changes to NiMARE.

**Comment by tsalo** [comment]
@JulioAPeraza this issue might be a good fit for you. It will involve perusing the commit histories of a number of NiMARE classes and functions, as well as release notes.

**Comment by JulioAPeraza** [comment]
@tsalo Would you like to have the directives `.. versionadded::` and `.. versionchaged::` at the top or the bottom of the docstring? [Sphinx decorators](https://deprecated.readthedocs.io/en/latest/sphinx_deco.html) (`@versionadded` and `@versionchaged`) put them at the bottom (after `See also`).

**Comment by tsalo** [comment]
I assumed at the top, but if the examples show them at the bottom then that's probably the best place for them.

**Comment by JulioAPeraza** [comment]
It seems that Sphinx decorators (`@versionadded` and `@versionchaged`) only append the directives to the docstring. I couldn't find a parameter in the class to force it to insert at the beginning. 
I will use the directives directly to write them at the top.
