### ISSUE TITLE
Add conjunction analysis example using nilearn

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#515]
## Summary

A question in today's OHBM NiMARE tutorial came up about conjunction analyses in NiMARE. These analyses should be possible with `nilearn.image.threshold_img` and `nilearn.image.math_img`, but it would be useful for NiMARE users if we had an example of how to do that in our documentation.

**Comment by alexenge** [comment]
We performed conjunction analyses [like this](https://github.com/SkeideLab/meta_semantics/blob/b2a10080243f24c84d40d25eb94673fee288a2e8/code/nb03_adults.py#L94) for our recent CBMA, trying to mirror the behavior of GingerALE (which also computes a conjunction image as the minimum ALE values [across groups] for all voxels that were significant in *both* individual group maps).

I'd be happy to try and contribute an example for the documentation but I feel like it would make sense to combine this with an example for a subtraction analysis (which, as far as I can see, isn't covered either at the moment). Of course, this would require either (a) a sensible second example data set that is complementary to the pain studies or (b) two completely new data sets that make for a meaningful subtraction/conjunction example. We could contribute our "semantic cognition in children" data (the Sleuth files are shared [here](https://github.com/SkeideLab/meta_semantics/tree/main/results/ale) anyways). Or would you prefer this to be based on an IBMA (in which case we could create new complementary data sets from Neurosynth)?

**Comment by tsalo** [comment]
That code snippet looks great, and it would be awesome if you could contribute an example!

> I'd be happy to try and contribute an example for the documentation but I feel like it would make sense to combine this with an example for a subtraction analysis (which, as far as I can see, isn't covered either at the moment).

I agree, a new example with both conjunction and subtraction analyses would be perfect.

> Of course, this would require either (a) a sensible second example data set that is complementary to the pain studies or (b) two completely new data sets that make for a meaningful subtraction/conjunction example. We could contribute our "semantic cognition in children" data (the Sleuth files are shared here anyways). Or would you prefer this to be based on an IBMA (in which case we could create new complementary data sets from Neurosynth)?

I like the idea of using your semantic cognition in children samples, if you're willing to store copies in NiMARE's example data. Plus, you can reference your preprint in the example!

**Comment by alexenge** [comment]
We're glad to have the relevant data shipped with NiMARE. I'll try to prepare a subtraction/conjunction example and will open a PR once it's ready.
