### ISSUE TITLE
cannot import name 'ImagesToCoordinates' from 'nimare.transforms'

### ISSUE THREAD

**Issue by andreifoldes** [neurostuff/NiMARE#529]
## Summary
There seems to be classes missing from the version that comes with pip...

## Additional details

- NiMARE version: 0.0.7

### What were you trying to do?
Run tutorial: https://nimare.readthedocs.io/en/latest/auto_examples/01_datasets/transform_images_to_coordinates.html
### What did you expect to happen?
Run tutorial
### What actually happened?
`ImportError: cannot import name 'ImagesToCoordinates' from 'nimare.transforms' (C:\Users\folde\miniconda3\lib\site-packages\nimare\transforms.py)`

**Comment by tsalo** [comment]
`ImagesToCoordinates` was added in 0.0.8. I would recommend updating to 0.0.8 or 0.0.9rc2.

**Comment by tsalo** [comment]
@andreifoldes did updating help?

**Comment by tsalo** [comment]
@andreifoldes please follow up if you have further issues, but I'm going to close this one.
