### ISSUE TITLE
DerSimonianLaird failing due to SVD not converging

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#542]
## Summary

DerSimonianLaird appears to be failing lately. I noticed this in the NHA tutorial (see neurohackademy/nh2021-curriculum#5).

I think this is due to some change made from `numpy` 1.21.0 (succeeds) to 1.21.1 (fails).

## Additional details

- NiMARE version: ~0.0.10rc1

### What were you trying to do?
Run the DerSimonianLaird IBMA Estimator on the pain dataset.

### What did you expect to happen?
The Estimator to run through without raising an exception.

### What actually happened?

Here's the full log from numpy 1.21.0 (some warnings, but no errors):

```
/Users/taylor/Documents/tsalo/nilearn/nilearn/datasets/__init__.py:92: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
INFO:nimare.utils:Shared path detected: '/Users/taylor/.nimare/nidm_21pain/'
INFO:nimare.utils:Shared path detected: '/Users/taylor/.nimare/nidm_21pain/'
/Users/taylor/Documents/tsalo/PyMARE/pymare/stats.py:23: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / (v + tau2)
/Users/taylor/Documents/tsalo/PyMARE/pymare/estimators/estimators.py:200: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / v
/Users/taylor/Documents/tsalo/nilearn/nilearn/datasets/struct.py:155: FutureWarning: Default resolution of the MNI template will change from 2mm to 1mm in version 0.10.0
  warnings.warn("Default resolution of the MNI template will change "
/Users/taylor/Documents/tsalo/nilearn/nilearn/_utils/niimg.py:61: UserWarning: Non-finite values detected. These values will be replaced with zeros.
  warn(
```

Here's the full log + traceback from numpy 1.21.1:

```
/Users/taylor/Documents/tsalo/nilearn/nilearn/datasets/__init__.py:92: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
INFO:nimare.utils:Shared path detected: '/Users/taylor/.nimare/nidm_21pain/'
INFO:nimare.utils:Shared path detected: '/Users/taylor/.nimare/nidm_21pain/'
/Users/taylor/Documents/tsalo/PyMARE/pymare/stats.py:23: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / (v + tau2)
/Users/taylor/Documents/tsalo/PyMARE/pymare/estimators/estimators.py:200: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / v
Traceback (most recent call last):
  File "plot_ibma.py", line 50, in <module>
    meta.fit(dset)
  File "/Users/taylor/Documents/tsalo/NiMARE/nimare/base.py", line 297, in fit
    maps = self._fit(dataset)
  File "/Users/taylor/Documents/tsalo/NiMARE/nimare/meta/ibma.py", line 282, in _fit
    est.fit_dataset(pymare_dset)
  File "/Users/taylor/Documents/tsalo/PyMARE/pymare/estimators/estimators.py", line 90, in fit_dataset
    self.fit(*args, **all_kwargs)
  File "/Users/taylor/Documents/tsalo/PyMARE/pymare/estimators/estimators.py", line 213, in fit
    beta_dl, inv_cov = weighted_least_squares(y, v, X, tau2=tau_dl,
  File "/Users/taylor/Documents/tsalo/PyMARE/pymare/stats.py", line 31, in weighted_least_squares
    precision = np.linalg.pinv(cov).T
  File "<__array_function__ internals>", line 5, in pinv
  File "/opt/miniconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 2002, in pinv
    u, s, vt = svd(a, full_matrices=False, hermitian=hermitian)
  File "<__array_function__ internals>", line 5, in svd
  File "/opt/miniconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 1660, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/opt/miniconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
Exception ignored in: <function ArrayProxy.__del__ at 0x7fa1b9322940>
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/nibabel/arrayproxy.py", line 173, in __del__
  File "/opt/miniconda3/lib/python3.8/site-packages/nibabel/openers.py", line 183, in close_if_mine
  File "/opt/miniconda3/lib/python3.8/site-packages/nibabel/openers.py", line 174, in close
  File "indexed_gzip/indexed_gzip.pyx", line 496, in indexed_gzip.indexed_gzip._IndexedGzipFile.close
AttributeError: 'NoneType' object has no attribute 'debug'
```

## Reproducing the bug
Run the `plot_ibma` example, in particular the following pieces:

```python
import os

import nimare
from nimare.meta import ibma
from nimare.tests.utils import get_test_data_path

dset_dir = nimare.extract.download_nidm_pain()
dset_file = os.path.join(get_test_data_path(), "nidm_pain_dset.json")
dset = nimare.dataset.Dataset(
    dset_file,
    mask="/Users/taylor/.nimare/nidm_21pain/pain_01.nidm/Mask.nii.gz")
dset.update_path(dset_dir)

# Calculate missing images
xformer = nimare.transforms.ImageTransformer(target=["varcope", "z"], overwrite=True)
dset = xformer.transform(dset)

# Run meta-analysis
meta = ibma.DerSimonianLaird()
meta.fit(dset)
```

**Comment by tsalo** [comment]
The only difference in the main dependency versions from [a working RTD build](https://readthedocs.org/projects/nimare/builds/14263685/) and [a failing one](https://readthedocs.org/projects/nimare/builds/14277272/) is numpy (working: numpy-1.21.0, failing: numpy-1.21.1), so the most recent release is worth looking into.

**Comment by nicholst** [comment]
I don't have much deep insight, but these back-to-back warnings are troubling:

```
/Users/taylor/Documents/tsalo/PyMARE/pymare/stats.py:23: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / (v + tau2)
/Users/taylor/Documents/tsalo/PyMARE/pymare/estimators/estimators.py:200: RuntimeWarning: divide by zero encountered in true_divide
  w = 1. / v
```

This is saying that *both* the study variance (`v`) and the estimated between study variance (`tau2`) are both zero, which is a mighty deginerate case... could this be related to masking problems?

**Comment by tsalo** [comment]
That makes sense. We currently replace any voxels with 0 in at least one study with 0 across all studies, to aggressively mask out any voxels that might not be covered by one or more of the studies:

https://github.com/neurostuff/NiMARE/blob/80642d1e2752943e5d4b3c325e1cfc356e50a8b6/nimare/base.py#L372-L377

That means that PyMARE often ends up getting inputs with zeros across all studies. It's not optimal, but I don't think we ever figured out a better solution.

**Comment by tyarkoni** [comment]
I believe the issue is that the voxel dimension is currently parallelized in PyMARE, which makes it very fast. The downside is that the current implementation can't handle NaNs, so we mask out videos with any NaNs as they would otherwise produce NaNs anyway. 

The ideal solution would be to reimplement the underlying computations using a NaN-tolerant approach. Next best would be to naively loop over voxels in NiMARE, do the masking there, pass only valid values to PyMARE, and then reconstruct. But obviously this would be several orders of magnitude slower...

**Comment by nicholst** [comment]
Hmm, OK.  Isn't the better solution to alter the mask at the outset, so we
don't even try to fit models at such voxels?

>

**Comment by nicholst** [comment]
Our messages crossed.

But it's a trivial thing to detect invalid voxels (1 or more 0's)... can't we alter the mask before even calling PyMARE?

**Comment by tsalo** [comment]
Yes, I believe so. We could either modify the `masker` attribute directly or include a secondary masker attribute so users' parameters aren't mysteriously changed. I can open a PR to address that pretty quickly.

Unfortunately, I don't think that will solve the SVD issue, since it was running fine with numpy `1.21.0`.

**Comment by tsalo** [comment]
Update: #544 should address the masking issue.

**Comment by tsalo** [comment]
Since merging #544, I can't reproduce the bug anymore, so it looks like I was wrong. Addressing the masking issue dealt with the SVD issue. Thanks @nicholst for identifying the problem!
