### ISSUE TITLE
`CorrelationDecoder` fails while checking the number of features

### ISSUE THREAD

**Issue by JulioAPeraza** [neurostuff/NiMARE#559]
## Summary

`CorrelationDecoder` fails while checking the number of features

## Additional details

- NiMARE version: ~0.0.10rc2

### What were you trying to do?

Train a `CorrelationDecoder` class object with all the features of the Neurosynth database.

### What did you expect to happen?
The `CorrelationDecoder.fit()` to run through without errors.

### What actually happened?
An error:
```
Traceback (most recent call last):
  File "test.py", line 66, in <module>
    decoder.fit(dset)
  File "/opt/anaconda3/lib/python3.8/site-packages/nimare/base.py", line 541, in fit
    self._fit(dataset)
  File "/opt/anaconda3/lib/python3.8/site-packages/nimare/decode/continuous.py", line 194, in _fit
    f"Decoding {feature} ({i}/{len(self.features)}): {len(feature_ids)}/"
TypeError: object of type 'NoneType' has no len()
```

## Reproducing the bug
```python
from nimare.decode.continuous import CorrelationDecoder
from nimare.meta.cbma import mkda

decoder = CorrelationDecoder(
    frequency_threshold=0.001,
    meta_estimator=mkda.MKDAChi2,
    target_image='z_desc-specificity',
)
decoder.fit(ns_dset)
```

**Comment by tsalo** [comment]
A minor note- this happens specifically when a list of features is not provided by the user (i.e., `features` is `None`).
