### ISSUE TITLE
`CorrelationDecoder.fit(dset)` fails to create temporary files on HPC compute nodes where $HOME is read-only 

### ISSUE THREAD

**Issue by alyssadai** [neurostuff/NiMARE#565]
## Summary
`CorrelationDecoder.fit()` fails when ran on Niagara cluster compute nodes, since it attempts to create temporary files in $HOME which is read-only.

## Additional details

- NiMARE version: 0.0.10rc2

It appears that [PR #460](https://github.com/neurostuff/NiMARE/pull/460) added the feature causing the bug.
Bug could be resolved by storing temporary files in $TMPDIR environment variable or /tmp.

### What were you trying to do?
Fit a `CorrelationDecoder` on a subset of the Neurosynth dataset.

### What did you expect to happen?
`CorrelationDecoder.fit()` to run through without errors; a file named "neurosynth_dataset_slice_decoded.csv" to be outputted.

### What actually happened?
An error:
```
Traceback (most recent call last):
  File "decode_example.py", line 14, in <module>
    decoder.fit(neurosynth_dset)
  File "/gpfs/fs1/home/m/mchakrav/daialy/.virtualenvs/nimare_venv/lib/python3.8/site-packages/nimare/base.py", line 548, in fit
    self._fit(dataset)
  File "/gpfs/fs1/home/m/mchakrav/daialy/.virtualenvs/nimare_venv/lib/python3.8/site-packages/nimare/decode/continuous.py", line 185, in _fit
    dataset = kernel_transformer.transform(dataset, return_type="dataset")
  File "/gpfs/fs1/home/m/mchakrav/daialy/.virtualenvs/nimare_venv/lib/python3.8/site-packages/nimare/utils.py", line 462, in memmap_context
    dataset_dir = _get_dataset_dir("temporary_files", data_dir=None)
  File "/gpfs/fs1/home/m/mchakrav/daialy/.virtualenvs/nimare_venv/lib/python3.8/site-packages/nimare/extract/utils.py", line 143, in _get_dataset_dir
    raise OSError(
OSError: NiMARE tried to store the dataset in the following directories, but: 
 -/home/m/mchakrav/daialy/.nimare/temporary_files (Read-only file system)
```

## Reproducing the bug

The following script was submitted as a job to SLURM, using [qbatch](https://github.com/pipitone/qbatch).
```python
#decode_images.py
import os
import nimare

out_dir = os.path.abspath("nimare_ns_data/")

neurosynth_dset = nimare.dataset.Dataset.load(os.path.join(out_dir, "neurosynth_dataset.pkl.gz"))
neurosynth_dset.update_path(out_dir)

neurosynth_dset = neurosynth_dset.slice(neurosynth_dset.ids[:50])
neurosynth_dset.annotations = neurosynth_dset.annotations[
    ["id", "study_id", "contrast_id", "terms_abstract_tfidf__11", "terms_abstract_tfidf__15"]
]

from nimare.decode import continuous
decoder = continuous.CorrelationDecoder(feature_group=None, features=None)
decoder.fit(neurosynth_dset)
decoded_df = decoder.transform("myimage.nii.gz")
decoded_df.to_csv("neurosynth_dataset_slice_decoded.csv")
```
qbatch command: `qbatch -c1 decode_joblist.txt`
contents of decode_joblist.txt:
```
python decode_images.py
```

**Comment by tsalo** [comment]
I agree that this is a great idea, although I will need to look into how other packages handle this issue. NiMARE has a dedicated data directory, based on `nilearn`'s approach when downloading files with its `datasets` module, so I'm not sure if a _temporary_ directory is the way to go, but there should be a way to configure or set that target location in any functions/classes that might use it.

**Comment by tsalo** [comment]
I think the problem might be one of documentation. I took the data-directory creation code from `nilearn`, and I've never really gotten familiar with it. However, `nimare.extract.utils.get_data_dirs()` attempts to use global variables (either `NIMARE_SHARED_DATA` or `NIMARE_DATA`). Obviously neither of those is `TMPDIR`, and without digging _deep_ into the code I doubt anyone would know about them. However, if we document them, then that might help folks.

An alternative would be to properly separate the temporary and data directories. I believe `nilearn` has a `memory` argument in a number of its functions, which we could use in NiMARE. Users can provide a path to a caching directory and temporary files will be written there.

**Comment by gdevenyi** [comment]
(technical staff supporting @alyssadai here). If there is indeed some environment variables which would impact this that would work fine, however my look over the documentation didn't immediately expose them (or as function options).

A separation of TMP directory would be beneficial in general, for using faster storage compared to other files.

**Comment by tsalo** [comment]
Thanks @gdevenyi. I'll make sure to document the data directory variable, and I'll also look into supporting a separate temporary directory.

**Comment by tsalo** [comment]
@alyssadai @gdevenyi, would you mind taking a look at the new documentation to see if it's clear enough?

The new page is https://nimare.readthedocs.io/en/latest/fetching.html#fetching-tools , and the pages that link to it are:
- https://nimare.readthedocs.io/en/latest/api.html#module-nimare.extract
- https://nimare.readthedocs.io/en/latest/auto_examples/01_datasets/download_neurosynth.html#sphx-glr-auto-examples-01-datasets-download-neurosynth-py

**Comment by alyssadai** [comment]
Hi Taylor, the documentation reads clearly to me - thanks for adding this. When `data_dir` is specified in the fetch call, would subsequent temporary files (e.g. for `CorrelationDecoder.fit()`) also be created in `{data_dir}/temporary_files`? Or are temporary files still directed to the home directory for now (looks like this might be the case based on [#569](https://github.com/neurostuff/NiMARE/issues/569))?
