### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#6]
Is there a set of dependencies I should limit NiMARE to? For one, I was thinking that [nltools.mask.create_spheres](http://neurolearn.readthedocs.io/en/latest/reference.html#nltools.mask.create_sphere) would make the KDA and MKDA kernel estimators much simpler, but I know that nltools is not as mature a package as something like nibabel.

**Comment by tyarkoni** [comment]
I don't see any problem including a large number of *optional* dependencies, but the default install should be pretty minimalistic. We should probably maintain separate sets of dependencies, and group them under `EXTRAS_REQUIRE` in `setup.py`. The default should be to install only what's necessary for *all* estimators (or any other core functionality); then we could at minimum have a `'full'` extras key that installs everything required by any of the estimators (and potentially intermediate levels if that makes sense).

**Comment by tyarkoni** [comment]
Re: nltools, I don't see immaturity as a problem so long as you're committed to updating NiMARE any time the nltools API changes and stuff breaks. As long as we have tests that cover the functionality in question, it seems fine to me.

**Comment by tsalo** [comment]
That makes sense. I'll use nltools for now, but we can always adapt the code from Neurosynth if nltools starts changing too much. I'll also start working on tests once I can get enough of the dataset code working that I can load the example database and play with that.

**Comment by tyarkoni** [comment]
Re-opening because it doesn't seem like all of the current dependencies are really required for core functionality. E.g., statsmodels, sklearn, cognitiveatlas, fuzzywuzzy, and probably a bunch of others are only required for certain estimators/tools. We should probably move these to `extras_require`.

I also note that the `EXTRAS_REQUIRES` variable in `version.py` currently isn't actually passed to `setup()`.

**Comment by tyarkoni** [comment]
Meh, on re-assessment, I think it's fine as-is.
