### ISSUE TITLE
Add cluster mass option for Monte Carlo FWE correction methods

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#608]
## Summary

I was reading the [FSL randomise documentation](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Randomise/UserGuide) and they referred to cluster size-based inference as "so passé!" Apparently, cluster mass-based inference is preferable, based on the documentation and on [Zhang, Nichols, & Johnson (2009)](https://dx.doi.org/10.1016%2Fj.neuroimage.2008.08.017), which I, embarrassingly, hadn't heard of.

It should be pretty easy to calculate maximum cluster mass in each Monte Carlo permutation and retain it in a new null distribution, but I want to make sure that a cluster mass option would be useful before implementing it.

@nicholst would you be willing to weigh in on this?

## Additional details

Presumably, this would be a better metric for cluster-level inference.

## Next steps

1. Discuss. If the proposed option is not useful, then close this issue. Otherwise, implement the other steps.
2. Calculate "cluster mass" within the Monte Carlo FWE correction methods.
3. Retain maximum cluster mass in a new null distribution.
4. Calculate cluster masses for the statistical map.
5. Output the cluster mass-based significance map in the resulting MetaResult.

**Comment by nicholst** [comment]
I never had seen this cheeky comment on the randomise page!  I must assume it is a reference to someone's preference for TFCE, not clustermass per se.

Anyway, yes, in my evaluations, clustermass has always had equivalent or superior power.  And, as it is so easy to compute, yes, I'd say worth implimenting.

The only trick, like TFCE, is that it depends on having a sensibly scaled statistic image.  Do we have a z-score like image to work with?  I mean, it is nonparameric, so it will work with any image, but it's just a good feature if possible.  

Also, FWIW, I would pin the better (nonparametric) reference for cluster mass inference to be: [Bullmore et al. (1999)](https://pubmed.ncbi.nlm.nih.gov/10193695/).

**Comment by nicholst** [comment]
OK...  let's forget the voxel-wise z-transformation.  I think it won't make much/any difference to final corrected cluster p-value anyway.

(And, just to clarify, this is still "cluster inference", just assessed with the "cluster mass statistic" as opposed to the "cluster size statistic".)
