### ISSUE TITLE
Deprecate Peaks2MapsKernel

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#615]
## Summary

I'm thinking that we might want to remove Peaks2Maps from NiMARE. I believe that @tyarkoni has brought this up in the past, but I pushed back because I thought it was cool. I still do think it's a cool tool, but it doesn't seem to get much use and it's just more code for me to maintain, so...

Before I do remove it, I want to make sure that it isn't important for anything. @adelavega are there any plans for Peaks2Maps in Neurosynth 2.0?

## Additional details

I've only ever gotten one NeuroStars question about Peaks2Maps (https://neurostars.org/t/issue-generate-modeled-activation-maps-with-peaks2maps/17656) and there haven't been any bug reports or feature requests relating to it from users. Therefore, I assume that Peaks2Maps doesn't get much use, but it does come with a maintenance cost. Tensorflow changes have caused problems in the past (e.g., #288). Those problems have been fairly straightforward to solve, but dealing with them might be completely unnecessary if no one is using this tool.

## Next steps

1. Discuss.
2. Deprecate `Peaks2MapsKernel` and all associated functions. Probably remove at 0.0.13 or 0.1- whichever comes first.

**Comment by adelavega** [comment]
Not to my knowledge. I think it's fine to deprecate, it seems slightly tangential to the rest of the package.

**Comment by tsalo** [comment]
No one's followed up with any concerns, so I think I'm going to move forward with this. I'll mark #616 as ready for review now and merge tomorrow if no one voices any concerns.
