### ISSUE TITLE
fetch_neuroquery failing

### ISSUE THREAD

**Issue by magdalenasabat** [neurostuff/NiMARE#639]
## Summary
fetch_neuroquery completes without error but returns no database

## Additional details

- NiMARE version: 
 "date": "2022-01-06T16:31:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e094f2eb70d75c3d3b455636303a9f2934b44ec",
 "version": "0.0.11"
-python3.9, spyder 5

## Reproducing the bug
minimal example

```
import os
from nimare.extract import fetch_neuroquery

out_dir = os.path.abspath("../example_data/")
os.makedirs(out_dir, exist_ok=True)

files = fetch_neuroquery(
    data_dir=out_dir,
    version="1",
    overwrite=True,
    source="combined",
    vocab="neuroquery7547",
    type="tfidf",
)

neuroquery_db = files[0]
```
returns 

```
    neuroquery_db = files[0]

IndexError: list index out of range
```

It seems like ``` _find_entities``` in ``` _fetch_database ``` doesn't find matching coordinate files. Maybe a problem with the "database_file_manifest.json"  file?

**Comment by tsalo** [comment]
I think this is a problem of documentation and poor error reporting. The "combined" (abstract + body + keywords + title) source is only available with the 6308 vocabulary. You should be able to use the following to fetch that version:

```python
files = fetch_neuroquery(
    data_dir=out_dir,
    version="1",
    overwrite=True,
    source="combined",
    vocab="neuroquery6308",
    type="tfidf",
)
```

Please let me know if that doesn't work.

That said, NiMARE should definitely raise a more informative exception, and the `fetch_neuroquery` documentation should probably describe the usable combinations of kwargs better. I'll try to open a PR to improve both elements soon.

**Comment by magdalenasabat** [comment]
Thanks a lot, works!

**Comment by tsalo** [comment]
I'm going to close this issue in favor of #640. Hopefully I'll have a fix by the next release.
