### ISSUE TITLE
NiMARE tutorial page

### ISSUE THREAD

**Issue by bilgelm** [neurostuff/NiMARE#64]
I took a stab at generating a Nipype-style tutorial page for NiMARE:
https://github.com/bilgelm/nimare_tutorial
https://bilgelm.github.io/nimare_tutorial/

To update the tutorials:
- fork the repo
- open index.ipynb (or any *.ipynb file inside notebooks/) in jupyter
- make edits inside the first cell, then run the first cell and save
- run update_pages.sh, which will generate an html file from each ipynb file
- push to GitHub
- in the GitHub repository Settings, set the GitHub Pages to be built from the `/docs` folder (thanks @djarecka for helping figure this out):
<img width="755" alt="screen shot 2019-01-15 at 4 28 16 pm" src="https://user-images.githubusercontent.com/7794814/51211113-93089700-18e2-11e9-8ee3-9918b0eaa283.png">
- I had to select a theme in order for the site to be published successfully, but this doesn't affect the layout
<br><br>

The tutorial is far from complete: 
- Most hyperlinks are just placeholders. (ATM only the "NiMARE" link under "Introduction" and the links under "Workflow Examples" lead to their respective pages. These pages themselves are not complete either.)
- Need logos. 
- Binder hasn't been set up.
- ipynb files in `https://github.com/neurostuff/NiMARE/tree/master/examples` have been copied into this tutorial repository. It'd be better to link them rather than make separate copies.
- Someone else (@tsalo ?) should take over ownership of this tutorials repo.

**Comment by tsalo** [comment]
This looks great, thank you! We can transfer ownership over to neurostuff, I think, so that it's under the same ownership as the package itself.

Can you also open a PR to this repo to add your information to the Zenodo file?
