### ISSUE TITLE
get_studies_by_label failing

### ISSUE THREAD

**Issue by psyhyh** [neurostuff/NiMARE#660]
## Summary
NameError: name 'get_studies_by_label' is not defined

## Additional details

- NiMARE version: 0.0.11
- python 3.6

### What were you trying to do?
Using terms to filter papers and doing a meta-analysis

### What did you expect to happen?
Get the ids of the filtered papers

### What actually happened?
Function 'get_studies_by_label' can not be found, which is given on the website of NiMARE.

## Reproducing the bug

```python
# Use neurosynth database
dset = Dataset.load("neurosynth_dataset_with_abstracts.pkl.gz")

#define target variables
ids = get_studies_by_label(labels='(child* | adolescen*) & (trauma* | maltreat* | abuse | advers* | neglect)', label_threshold=0.001)
dset_sel = dset.slice(ids)
print(len(ids))

#do meta-analysis with ALE 
from nimare.meta.cbma.ale import ALE

meta = ALE()
results = meta.fit(dset_sel)

corr = FWECorrector(method="montecarlo", n_cores=8)
cres = corr.transform(results)

plot_stat_map(
    results.get_map("z"),
    cut_coords=[0, 0, -8],
    draw_cross=False,
    cmap="RdBu_r",
    threshold=0.1,
)
plot_stat_map(
    cres.get_map("z_desc-size_level-cluster_corr-FWE_method-montecarlo"),
    cut_coords=[0, 0, -8],
    draw_cross=False,
    cmap="RdBu_r",
    threshold=0.1,
)
```
I tried to do the same thing on NiMARE as I did on NeuroSynth but it reported errors. If the function 'get_studies_by_label' did not work, how could I filter papers by terms?

**Comment by psyhyh** [comment]
> In order to understand the nature of your problem, it would be helpful to have the code you used. Can you share the minimal code necessary to reproduce the issue?

I have add the code in the issue in triple back-ticks('''), but I don't why it disappeared,

**Comment by psyhyh** [comment]
> Thank you.
> 
> There are two issues that I can see:
> 
> 1. `get_studies_by_label` is not a function in NiMARE. It is actually a method of the Dataset class. You can see a bit more about it [in this example](https://nimare.readthedocs.io/en/latest/auto_examples/01_datasets/01_plot_dataset_io.html#datasets-support-many-search-methods), but the gist is that you need to do `dset.get_studies_by_label()` instead.
> 2. NiMARE's version of `get_studies_by_label` doesn't support the advanced searches that Neurosynth did.
>    
>    * The main reason for this is that we want most search capabilities to happen online, using Neurosynth 2.0 (once it's operational).
>    * Also, Tal considered the search method he implemented in Neurosynth buggy.
> 
> If you want to reproduce your search with NiMARE, you will need to search for individual labels and then combine the lists of IDs based on the search pattern.
> 
> For example, to get the `(child* | adolescen*)` part of the search, you could do the following:
> 
> ```python
> all_labels = dset.get_labels()
> # NiMARE labels start with a label group (e.g., terms_abstract_tfidf__) followed by the label
> child_labels = [label for label in all_labels if "__child" in label]
> adolescen_labels =  [label for label in all_labels if "__ adolescen" in label]
> c_or_a_labels = child_labels + adolescen_labels
> child_or_adolescen_ids = []
> for label in c_or_a_labels:
>     label_ids = dset.get_studies_by_label(label, 0.001)
>     child_or_adolescen_ids += label_ids
> 
> child_or_adolescen_ids = sorted(list(set(child_or_adolescen_ids)))
> ```

Thank you for your kind reply, I'll try it later cause it's too late.

**Comment by psyhyh** [comment]
Hey, Taylor. I met another problem that I could not understand. I use your code 

> child_labels = [label for label in all_labels if "__child" in label]
> adolescen_labels =  [label for label in all_labels if "__ adolescen" in label]
...
>len(child_or_adolescen_ids)

It returned 738.
I found there was a space in "__ adolescen", and I deleted it. Then it returned 1121. 
I think it may be similar to this: https://neurostars.org/t/nimare-neurosynth-complex-features-meta-analysis/19172/9.
But I do not figure out why.

**Comment by psyhyh** [comment]
One more question was that I met an error "ValueError: No objects to concatenate" when I ran meta-analysis. The full code was as follows. The error appeared in the last part.
My aim was to do a complex features meta-analysis. Could you please give me some suggestions about that error and the code? Thank you.

# import and read data
import nimare, os
dset_file = "neurosynth_dataset_with_abstracts.pkl.gz"
basedir = os.path.dirname(dset_file)
update_path = os.path.join(basedir, "D:\\PHD_design\\NiMARE", dset_file)
dset = nimare.dataset.Dataset.load(update_path)

# Get labels
all_labels = dset.get_labels()
# Get studies id of childhood
child_labels = [label for label in all_labels if "__child" in label]
adolescen_labels = [label for label in all_labels if "__adolescen" in label]
c_or_a_labels = child_labels + adolescen_labels
child_or_adolescen_ids = []
for label in c_or_a_labels:
    label_ids = dset.get_studies_by_label(label, 0.001)
    child_or_adolescen_ids += label_ids

child_or_adolescen_ids = sorted(list(set(child_or_adolescen_ids)))

# Get studies id of schizophrenia
schizophrenia_labels = [label for label in all_labels if "__schizophrenia" in label]
psychosis_labels = [label for label in all_labels if "__psychosis" in label]
schizophrenia_labels = schizophrenia_labels + psychosis_labels
schizophrenia_ids = []
for label in schizophrenia_labels:
    label_ids = dset.get_studies_by_label(label, 0.001)
    schizophrenia_ids += label_ids

schizophrenia_ids = sorted(list(set(schizophrenia_ids)))

# Get studies id of schizophrenia and childhood
childhood_and_schizophrenia_ids=[]
for id in child_or_adolescen_ids:
    if(id in schizophrenia_ids):
        childhood_and_schizophrenia_ids += id

# Get dataset of childhood and schizophrenia
label_childhood_and_schizophrenia_dset = dset.slice(childhood_and_schizophrenia_ids)

# Do meta-anlysis
from nimare.meta.cbma.ale import ALE
meta = ALE()
results = meta.fit(label_childhood_and_schizophrenia_dset)
corr = FWECorrector(method="montecarlo", n_cores=8)
cres = corr.transform(results)

**Comment by tsalo** [comment]
>I found there was a space in "__ adolescen", and I deleted it. Then it returned 1121.

Yes, it looks like that was a typo on my part. I'm pretty sure there are no labels with `__ adolscen` in them, so the difference in the number of identified studies is due to the fact that no `adolescen*` labels were being selected.

>Could you please give me some suggestions about that error and the code?

```python
# Get studies id of schizophrenia and childhood
childhood_and_schizophrenia_ids=[]
for id in child_or_adolescen_ids:
    if(id in schizophrenia_ids):
        childhood_and_schizophrenia_ids += id
```

As simpler alternative would be:

```python
childhood_and_schizophrenia_ids = list(set(child_or_adolescen_ids).intersection(schizophrenia_ids)))
```

Regarding the error, can you share the full traceback? Also, can you share the string returned by `print(dset)` for each of the Datasets you created?

**Comment by psyhyh** [comment]
The full traceback was as follows:
'''
results = meta.fit(label_childhood_and_schizophrenia_dset)
INFO:nimare.dataset:Retaining 0/440 studies
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\psyhy\AppData\Local\Programs\Python\Python36\lib\site-packages\nimare\base.py", line 312, in fit
    self._validate_input(dataset, drop_invalid=drop_invalid)
  File "C:\Users\psyhy\AppData\Local\Programs\Python\Python36\lib\site-packages\nimare\base.py", line 262, in _validate_input
    data = dataset.get(self._required_inputs, drop_invalid=drop_invalid)
  File "C:\Users\psyhy\AppData\Local\Programs\Python\Python36\lib\site-packages\nimare\dataset.py", line 428, in get
    results[k] = pd.concat(results[k])
  File "C:\Users\psyhy\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\reshape\concat.py", line 284, in concat
    sort=sort,
  File "C:\Users\psyhy\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\reshape\concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
'''

For each of the Datasets: 
>>> print(dset) #print the whole dset
Dataset(14371 experiments, space='mni152_2mm')
>>> print(label_childhood_and_schizophrenia_dset)
Dataset(440 experiments, space='mni152_2mm')

Another more question is that whether I can do meta-analysis using both Neurosynth and NeuroQuery at the same time, but removing the repeat study.

**Comment by psyhyh** [comment]
Thank you for your patient guidance! It seems that most of problems have been solved. Maybe the last one is this:
```
from nimare.meta.cbma.ale import ALE
>>> meta = ALE(kernel__sample_size=20)
>>> results = meta.fit(label_childhood_and_schizophrenia_dset)
**WARNING**:nimare.utils:Metadata field 'sample_sizes' not found. Set a constant value for this field as an argument, if possible.
```
But it seems that there is a sample size.
```
>>> print(meta)
ALE(kernel_transformer=ALEKernel(sample_size=20))
```
And if I run the test, it will stop at here:
```
>>> from nimare.correct import FWECorrector
>>> corr = FWECorrector(method="montecarlo", n_iters=10, n_cores=8)
>>> cres = corr.transform(results)
INFO:nimare.correct:Using correction method implemented in Estimator: nimare.meta.cbma.ale.ALE.correct_fwe_montecarlo.
  0%|                                                                                           | 0/10 [00:00<?, ?it/s]
```

**Comment by tsalo** [comment]
>But it seems that there is a sample size.

That warning is specifically referring to the lack of a study-wise sample size in the Dataset metadata, so it's okay as long as you provided one yourself (which you did).

>And if I run the test, it will stop at here:

It might just be taking a very long time to run. How many studies are in the dataset now?

**Comment by psyhyh** [comment]
> How many studies are in the dataset now?
44 studies

**Comment by tsalo** [comment]
Only 44? It definitely shouldn't take long to run FWE correction such a small Dataset...

**Comment by psyhyh** [comment]
In the method of list.intersection，it combines schizophrenia（700+）and childhood （1100+), and gets a total of 44 ids.

**Comment by psyhyh** [comment]
> Only 44? It definitely shouldn't take long to run FWE correction such a small Dataset...
```
>>> from nimare.correct import FWECorrector
>>> corr = FWECorrector(method="montecarlo", n_iters=10, n_cores=8)
>>> cres = corr.transform(results)
```
Maybe I figured out why. As mentioned earlier, the code above will get stuck without error report. That's werid. If I change the iterations to default (I think it's 10000), it will report a lot of  memory errors, and the terminal will shut down. 
When I change n_cores to 1, it works normally. But I do set n_cores=8 in R language without error report, maybe it doesn't not work in Python.
```
from nimare.correct import FWECorrector
corr = FWECorrector(method="montecarlo", n_cores=1)
cres = corr.transform(results)
```
The result without corrector makes sense with a lot of activation areas, while the result after FWE correction has a  very very small activation area. What can I do to increase the area of activation? Or it's just due to the small sample of results.

**Comment by psyhyh** [comment]
Thank you for your patience! You solved all my questions! What an amazing man you are!
