### ISSUE TITLE
Add CLI to build script from meta-analysis specification file

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#664]
## Summary

Neurostore will generate JSON files specifying the steps of a meta-analysis. We will need an interface in NiMARE to translate the JSON file to a script using NiMARE code. It should be as simple for the user as providing the JSON file to a NiMARE CLI.

**Comment by jdkent** [comment]
this is being completed in the nsc-runner: https://github.com/neurostuff/nsc-runner
