### ISSUE TITLE
Should we use NIDM-Results?

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#7]
NIDM-Results objects contain all of the information we could need from contrasts for NiMARE, plus the tools for parsing those objects (i.e., [PyNIDM](https://github.com/incf-nidash/PyNIDM)) seem pretty useful. I don’t know how stable the specification or the tools are (it looks like both are under constant development), but it seems like we could build the NiMARE database/dataset classes around the NIDM-Results objects.

I also don’t know whether it's possible or not to build the Results objects with partial information (e.g., just coordinates and metadata), but NeuroVault supports them and we could request that Brainspell output its database in that format as well. That should make it easier to download and merge everything, not to mention it would automatically link SE and contrast images for IBMAs (which has been something that's been vexing me).

**Comment by chrisfilo** [comment]
I think it would be interesting to explore this. Indeed NIDM-Results format allows to store both contrast images and error maps. The downside is that it uses technologies with a bit of a steep learning curve.

**Comment by tsalo** [comment]
Yeah... after looking at the different repositories `incf-nidash` has out there in a little more depth, I couldn't find anything for reading in NIDM-Results folders. Maybe I'm missing something, but it's hard to figure out what each library can do with the current documentation.

**Comment by tsalo** [comment]
I wrote a very simple notebook [here](https://github.com/tsalo/NiMARE/blob/skeleton-expansion/examples/save_nidm_to_dset.ipynb) to read in a folder containing a collection of NIDM-Results packs (in this case the [21 pain studies collection](https://www.neurovault.org/collections/1425/) from NeuroVault) and convert it to a NiMARE-compatible json file. It might be useful jumping-off point for a future version of the NeuroVaultExtractor we plan to implement in NiMARE.

**Comment by chrisfilo** [comment]
AFAIK NIDM-Results does not make any guarantees about file naming conventions. To get the necessary files you need to parse the `.ttl` file: https://www.neurovault.org/collections/1425/pain_01.nidm.ttl

@cmaumet might know about python functions to help with parsing ttl. There is also some code in NV for this https://github.com/NeuroVault/NeuroVault/blob/c2975e35bec13dc36d694ac9894b57935b83627b/neurovault/apps/statmaps/nidm_results.py

**Comment by tsalo** [comment]
Oh... darn. Thanks for the heads up, though, and the NeuroVault code looks like it could be very helpful. I hadn't come across it before.

**Comment by cmaumet** [comment]
Hi @tsalo! I am sorry your experience with NIDM has not been great so far. 

 - Our Python library to read/write NIDM-Results packs is [nidmresults](https://github.com/incf-nidash/nidmresults). (But you were right, eventually this code should live in pyNIDM). I am currently updating this library to ease reading of NIDM-Results pack.
 - The other solution is to write queries, that's the approach we used for the NIDM-Results paper: e.g. [image_based_meta_analysis.py#L43-L94](https://github.com/incf-nidash/nidmresults-paper/blob/master/image_based_meta_analysis.py#L43-L94).

Can I get back to you when I have a first version of the reading implemented in the nidmresults library? I would love to get feedback!

More generally, if you have recommendations on how we could make the overall NIDM documentation more welcoming that would be very much appreciated. The most updated info is located in the README of the nidm-specs repository: https://github.com/incf-nidash/nidm-specs.

@chrisfilo: thanks a lot for pinging me!

**Comment by tsalo** [comment]
Hi @cmaumet. Thank you so much. NIDM is extremely cool, it just seems to have a steep learning curve. I am planning to become more familiar with the specifications and tools, so I would be happy to provide feedback on whatever stumbling blocks I encounter in the documentation as I learn.

I didn't realize nidmresults was meant to read the Results packs as well as write them, but that's great to hear. I can definitely wait until the reading functionality in nidmresults is ready, and will be excited to use it in NiMARE when that happens.

**Comment by tsalo** [comment]
I've pushed this to https://github.com/neurostuff/pyNIMADS/issues/1. This way we can still work on a NIMADS module prior to splitting it off into its own package, but we don't need to support NIDM-Results until it _is_ its own package.
