### ISSUE TITLE
Integrate Coordinate Based Meta Regression into NiMARE

### ISSUE THREAD

**Issue by nicholst** [neurostuff/NiMARE#700]
## Summary
@yifan0330 and @nicholst are developing "Coordinate Based Meta Regression" (CBMR) a new coordinate based meta-analysis method that has an explicit spatial (generative) model, and allows for comparing 2 or more (unbalanced) groups, while accounting for study-level regressors.  This issue concerns the efforst to integrate @yifan0330's code into the NiMARE code base.

## Additional details
Give access to NiMARE to this CBMR.

## Next steps
At the OHBM 2022 Hackathon @yifan0330 will work with @tsalo and others on this effort.

**Comment by tsalo** [comment]
@yifan0330 is [`yifan0330/Meta_regression_CBMA`](https://github.com/yifan0330/Meta_regression_CBMA) the up-to-date implementation of your method?

**Comment by yifan0330** [comment]
Sorry it's not a up-to-date implementation of our CBMR, I will update it soon!
