### ISSUE TITLE
Numbafy the code

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/NiMARE#72]
@tsalo have you tried using Numba's JIT compiler to speed up parts of the meta-analytic computations? The stuff in `stats` will almost certainly benefit. The large estimator classes/functions like `_run_ale` probably won't improve much right now, but we should try to re-factor into smaller (and ideally reusable) chunks with an eye to numbafication.

**Comment by tsalo** [comment]
I tried it in parts of ALE (especially `compute_ma`) in the past but didn't see any improvements (see https://github.com/NBCLab/pyale/issues/7 and https://github.com/NBCLab/pyale/pull/10). That said, I think it would be worth it to take another crack at it.

**Comment by tyarkoni** [comment]
Now that PyMARE can vectorize over voxels, this seems less useful, so closing for now.
