### ISSUE TITLE
stouffers and rfx_glm do not use parallelization

### ISSUE THREAD

**Issue by chrisgorgo** [neurostuff/NiMARE#74]

**Comment by tsalo** [comment]
Maybe we can use functors for this and #73. I don't know if it's possible to make a class callable without creating an instance, but that would allow us to have a private function for the permutations that can be called with multiprocessing, the same way we do it for ALE and other CBMA algorithms.

**Comment by tyarkoni** [comment]
Haven't thought about this at length, but this might be better handled with a `@parallelize` decorator or something like that, assuming the parallelization code is fairly consistent, or can be easily parameterized. It may be worth looking at [deco](https://github.com/alex-sherman/deco).

**Comment by tyarkoni** [comment]
Closing this, as we'll get parallelization for free now once we wrap PyMARE.
