### ISSUE TITLE
Release of Nilearn 0.10.0 has matplotlib>3.3.0 requirement

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#755]
## Summary

NiMARE only requires matplotlib version of greater than 3.2.0, which can lead to invalid installs of NiMARE with nilearn 0.10.0

## Additional details

- NiMARE version: 0.0.12

**Comment by tsalo** [comment]
Is there a conflict? Won't pip resolve the dependencies to >3.30?

**Comment by jdkent** [comment]
I think pip still has embedded resolution issues depending on the order of dependencies.

In environments where a version of matplotlib is already installed (e.g., google collab), pip does not retroactively update the version of matplotlib. 

example: https://colab.research.google.com/drive/1vCtrBPX4bFWE1bYBkLnLXe2QMTJBlNPd?usp=sharing

I think this may also be fixed by placing nilearn above the matplotlib requirement, but that would mean the dependencies are no longer alphabetically organized.
