### ISSUE TITLE
support nibabel 5.0.0+

### ISSUE THREAD

**Issue by jdkent** [neurostuff/NiMARE#759]
## Summary

related to #758, after merging #757. we do not support nibabel 5.0.0 because of test failures.
## Additional details

supporting nibabel 5.0.0
## Next steps

identify places where we pass an int array into a nifti object

> Passing an int64 array to Nifti1Image without a header or dtype argument will raise a ValueError

**Comment by tsalo** [comment]
Probably good to use float32s instead of floats as well, I think.
