### ISSUE TITLE
Version 0.0.13 fails with older numba version

### ISSUE THREAD

**Issue by dlevitas** [neurostuff/NiMARE#766]
## Summary
I didn't encounter this in version `0.0.12`, but in the newest version, an older `numba` version seems to result in NiMARE failing.
## Additional details

- NiMARE version: `0.0.13`

### What were you trying to do?
Perform ALE meta-analysis

### What did you expect to happen?
Completion without error

### What actually happened?
Upon execution, immediately received an error: `expected dtype int64, got 'numpy.dtype[int64]'`

My installed `numba` version was `0.50.1`, upgrading to the most recent version (`0.56.4`) fixed the issue. I'm unsure however how old the `numba` version needs to be before triggering this error.  

## Reproducing the bug
Using NiMARE version `0.0.13`, run [this code snippet](https://neurostars.org/t/nimare-ale-fwecorrector-voxel-threshold/24598?u=dlevitas), with `numba` version `0.50.1`. Slightly newer `numba` may also trigger the error.

Would be happy to submit a PR to the setup.cfg file specifying a `numba` version.

**Comment by JulioAPeraza** [comment]
I can't reproduce this bug. I installed numba 0.50.1 and nimare 0.0.13, and the code linked above ran successfully.

**Comment by dlevitas** [comment]
There must have been some other versioning issue I was unaware of that was inadvertently corrected. Since this can't be reproduced, I'll close this issue.
