### ISSUE TITLE
Add `save()` and `load()` methods to `MetaResult` objects.

### ISSUE THREAD

**Issue by JulioAPeraza** [neurostuff/NiMARE#770]
## Summary

@tsalo I was wondering if it would be possible to add `save()` and `load()` methods to `MetaResult` objects.

## Additional details

Having access to a `MetaResult` object will allow us to run diagnostics on results without needing to re-run an estimator and corrector. 

## Next steps

Replace `object` with `NiMAREBase` in:
https://github.com/neurostuff/NiMARE/blob/9998c7fc08cfaedbb2f9870484bc77b82ec2d0cd/nimare/results.py#L15-L17

**Comment by tsalo** [comment]
I definitely would love to have that, but I think I had pickling issues when I tried that in the past. If you can get it working that would be amazing.
