### ISSUE TITLE
Replace `m2r` with a package that is maintained

### ISSUE THREAD

**Issue by JulioAPeraza** [neurostuff/NiMARE#795]
## Summary

Switch from `m2r` to `m2r2` or `sphinx-mdinclude`.

## Additional details

`m2r` was archived and thus no longer maintained. That also prevents us to upgrade `mistune`, which is used by other dependencies.

https://github.com/neurostuff/NiMARE/blob/4ceb3589820801d852ece67dbb1adacdbf77f7b3/setup.cfg#L64-L67

## Next steps

Switch to [m2r2](https://github.com/crossnox/m2r2) or [sphinx-mdinclude](https://github.com/omnilib/sphinx-mdinclude). `sphinx-mdinclude` at least works with mistune 2.x.

**Comment by jdkent** [comment]
I do not have a strong opinion, m2r2 has more stars, but sphinx-mdinclude appears to be more focused as a sphinx-extension which is our use-case
