### ISSUE TITLE
Add similarity-sorted correlation matrix figure to IBMA reports

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#847]
## Summary

One issue with images on NeuroVault is that the contrast is not always clear or correctly labeled.
I was thinking that something that could help diagnose inverted contrasts would be a similarity-sorted correlation matrix figure, like the one in the [NARPS paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7771346/) that helped identify which processing pipelines gave inverted results to the others? It might be useful for flagging images with the wrong contrast (see below).

I don't necessarily think this would need clusters.

It could alternatively be a diagnostic of some kind.

![image](https://github.com/neurostuff/NiMARE/assets/8228902/8eb58e03-92a2-4fda-9fbf-c2be57cc1116)

**Comment by JulioAPeraza** [comment]
@tsalo Should we show the entire matrix or only the upper triangle?

**Comment by tsalo** [comment]
I think either would work. The upper triangle probably takes up less space though, so maybe try that first?
