### ISSUE TITLE
nilearn 0.10.3  breaks nimare

### ISSUE THREAD

**Issue by adelavega** [neurostuff/NiMARE#872]
```
     9 import pymare
     10 from joblib import Memory
---> 11 from nilearn._utils.niimg_conversions import _check_same_fov
     12 from nilearn.image import concat_imgs, resample_to_img
     13 from nilearn.input_data import NiftiMasker

ImportError: cannot import name '_check_same_fov' from 'nilearn._utils.niimg_conversions' (/usr/local/lib/python3.10/dist-packages/nilearn/_utils/niimg_conversions.py)
```

**Comment by Remi-Gau** [comment]
yeah we did 'some' clean up of how some internal functions were named:

- https://github.com/nilearn/nilearn/pull/4168
- https://github.com/nilearn/nilearn/pull/4086
- https://github.com/nilearn/nilearn/pull/4167
- https://github.com/nilearn/nilearn/pull/4166

**Comment by adelavega** [comment]
yep! got that taken care of in #873 

our fault for relying on private functions

**Comment by Remi-Gau** [comment]
> our fault for relying on private functions

Well I would be throwing stones in a glass house if I said I have never used private functions from another library. 😜

**Comment by Remi-Gau** [comment]
The bug for the color bar issue should be fixed now.

FYI we have a few more bugs to fix before we can cut a bug fix release:
https://github.com/nilearn/nilearn/milestone/27

Not sure how easily you can test Nimare using Nilearn from main, to see that things are now good on your end.
